project: 
  type: website
  output-dir: docs

website:
  title: "Anissa Waller Del Valle: Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.qmd
          - text: "READy Exercise"
            href: ready-exercise/report.html
          - text: "Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "CDC Data Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Fitting Exercise"
            file: fitting-exercise/fitting-exercise.qmd
          - text: "ML Models Exercise"
            file: ml-models-exercise/ml-models-exercise.qmd
      - icon: github 
        href: https://github.com/anissawdv/anissawallerdelvalle-portfolio        
format:
  html:
    theme: lumen
    highlight: zenburn
    css: styles.css
    toc: FALSE