<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Analysis Assessment – Anissa Waller Del Valle: Data Analysis Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-051849a2a1e0f68eed7367b8dc269a5d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Anissa Waller Del Valle: Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/starter-analysis-exercise.html">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/anissawdv/anissawallerdelvalle-portfolio"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Analysis Assessment</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Load the needed packages. For this assignment, I used the dslabs package, the tidyverse package, and the ggplot2 package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dslabs"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Running the next command in the R console to seek information/assistance on gapminder.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># help(gapminder)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The str() function in R is short for structure. Running this command enables users to display the internal structure of an R object. I will run this command to display the structure of the gapminder dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># display structure of dataset</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(gapminder)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10545 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...
 $ infant_mortality: num  115.4 148.2 208 NA 59.9 ...
 $ life_expectancy : num  62.9 47.5 36 63 65.4 ...
 $ fertility       : num  6.19 7.65 7.32 4.43 3.11 4.55 4.82 3.45 2.7 5.57 ...
 $ population      : num  1636054 11124892 5270844 54681 20619075 ...
 $ gdp             : num  NA 1.38e+10 NA NA 1.08e+11 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 4 1 1 2 2 3 2 5 4 3 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 19 11 10 2 15 21 2 1 22 21 ...</code></pre>
</div>
</div>
<p>The summary command in R produces summary statistics for a given dataset or vector. I will obtain a summary of the data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain summary          </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gapminder)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                country           year      infant_mortality life_expectancy
 Albania            :   57   Min.   :1960   Min.   :  1.50   Min.   :13.20  
 Algeria            :   57   1st Qu.:1974   1st Qu.: 16.00   1st Qu.:57.50  
 Angola             :   57   Median :1988   Median : 41.50   Median :67.54  
 Antigua and Barbuda:   57   Mean   :1988   Mean   : 55.31   Mean   :64.81  
 Argentina          :   57   3rd Qu.:2002   3rd Qu.: 85.10   3rd Qu.:73.00  
 Armenia            :   57   Max.   :2016   Max.   :276.90   Max.   :83.90  
 (Other)            :10203                  NA's   :1453                    
   fertility       population             gdp               continent   
 Min.   :0.840   Min.   :3.124e+04   Min.   :4.040e+07   Africa  :2907  
 1st Qu.:2.200   1st Qu.:1.333e+06   1st Qu.:1.846e+09   Americas:2052  
 Median :3.750   Median :5.009e+06   Median :7.794e+09   Asia    :2679  
 Mean   :4.084   Mean   :2.701e+07   Mean   :1.480e+11   Europe  :2223  
 3rd Qu.:6.000   3rd Qu.:1.523e+07   3rd Qu.:5.540e+10   Oceania : 684  
 Max.   :9.220   Max.   :1.376e+09   Max.   :1.174e+13                  
 NA's   :187     NA's   :185         NA's   :2972                       
             region    
 Western Asia   :1026  
 Eastern Africa : 912  
 Western Africa : 912  
 Caribbean      : 741  
 South America  : 684  
 Southern Europe: 684  
 (Other)        :5586  </code></pre>
</div>
</div>
<p>The class() function in R determines the class (i.e., data type or structure) of an object. I will determine the type of object gapminder is.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># determine object type</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(gapminder)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p>I will write code that assigns only the African countries to a new object called africadata.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># assign African countries to new object          </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>africadata <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">filter</span>(continent <span class="sc">==</span> <span class="st">"Africa"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>&lt;- is an assignment operator. It will assign the filtered data to a new object, which I have named africadata.</p></li>
<li><p>gapminder is the dataset being used. %&gt;% is a pipe operator. It will take the output of one function and use it as the input to the next function.</p></li>
<li><p>filter() is a function that selects a subset of rows from a dataset that met specific conditions. It is part of the tidyverse collection.</p></li>
<li><p>continent == “Africa” is the condition being used inside filter(). It will keep rows where the continent coloumn is equal to “Africa”. Africa must be in quotes because it is a text string.</p></li>
</ul>
<p>I will check the new data set using the str and summary functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africadata) <span class="co"># structure of data</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 2 3 18 22 26 27 29 31 32 33 ...
 $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...
 $ infant_mortality: num  148 208 187 116 161 ...
 $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...
 $ fertility       : num  7.65 7.32 6.28 6.62 6.29 6.95 5.65 6.89 5.84 6.25 ...
 $ population      : num  11124892 5270844 2431620 524029 4829291 ...
 $ gdp             : num  1.38e+10 NA 6.22e+08 1.24e+08 5.97e+08 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 11 10 20 17 20 5 10 20 10 10 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africadata) <span class="co"># summary of data</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         country          year      infant_mortality life_expectancy
 Algeria     :  57   Min.   :1960   Min.   : 11.40   Min.   :13.20  
 Angola      :  57   1st Qu.:1974   1st Qu.: 62.20   1st Qu.:48.23  
 Benin       :  57   Median :1988   Median : 93.40   Median :53.98  
 Botswana    :  57   Mean   :1988   Mean   : 95.12   Mean   :54.38  
 Burkina Faso:  57   3rd Qu.:2002   3rd Qu.:124.70   3rd Qu.:60.10  
 Burundi     :  57   Max.   :2016   Max.   :237.40   Max.   :77.60  
 (Other)     :2565                  NA's   :226                     
   fertility       population             gdp               continent   
 Min.   :1.500   Min.   :    41538   Min.   :4.659e+07   Africa  :2907  
 1st Qu.:5.160   1st Qu.:  1605232   1st Qu.:8.373e+08   Americas:   0  
 Median :6.160   Median :  5570982   Median :2.448e+09   Asia    :   0  
 Mean   :5.851   Mean   : 12235961   Mean   :9.346e+09   Europe  :   0  
 3rd Qu.:6.860   3rd Qu.: 13888152   3rd Qu.:6.552e+09   Oceania :   0  
 Max.   :8.450   Max.   :182201962   Max.   :1.935e+11                  
 NA's   :51      NA's   :51          NA's   :637                        
                       region   
 Eastern Africa           :912  
 Western Africa           :912  
 Middle Africa            :456  
 Northern Africa          :342  
 Southern Africa          :285  
 Australia and New Zealand:  0  
 (Other)                  :  0  </code></pre>
</div>
</div>
<p>I confirmed there are now 2,907 observations. Now, I will take the africadata object and create two new objects. One object will contain infant_mortality and life_expectancy data. The other will contain population and life_expectancy. I should have two objects with 2,907 observations and two variables.</p>
<p>I will generate an object with only infant_mortality and life_expectancy</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create object with only infant mortality and life expectancy          </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>africa_infantmort_lifeexp <span class="ot">&lt;-</span> africadata <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">select</span>(infant_mortality, life_expectancy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>africa_infantmort_lifeexp will be the new object with only infant_mortality and life_expectancy.</p></li>
<li><p>&lt;- is an assignment operator and will assign the filtered data to the new object, africa_infantmort_lifeexp.</p></li>
<li><p>africadata is the dataset being used.</p></li>
<li><p>select() is a function that will grab a specific coloumn(s) from a dataset, enabling users to create a new dataset that contains only the columns selected.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># displau structure</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africa_infantmort_lifeexp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  2 variables:
 $ infant_mortality: num  148 208 187 116 161 ...
 $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain summary</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africa_infantmort_lifeexp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> infant_mortality life_expectancy
 Min.   : 11.40   Min.   :13.20  
 1st Qu.: 62.20   1st Qu.:48.23  
 Median : 93.40   Median :53.98  
 Mean   : 95.12   Mean   :54.38  
 3rd Qu.:124.70   3rd Qu.:60.10  
 Max.   :237.40   Max.   :77.60  
 NA's   :226                     </code></pre>
</div>
</div>
<p>I have confirmed that the above dataset, africa_infantmort_lifeexp, has 2,907 observations of 2 variables. I will now repeat the process described above to generate the second object with population and life_expectancy</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create object with population and life expectancy          </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>africa_pop_lifeexp <span class="ot">&lt;-</span> africadata <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">select</span>(population, life_expectancy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># display structure of data</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africa_pop_lifeexp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   2907 obs. of  2 variables:
 $ population     : num  11124892 5270844 2431620 524029 4829291 ...
 $ life_expectancy: num  47.5 36 38.3 50.3 35.2 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain summary of data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africa_pop_lifeexp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   population        life_expectancy
 Min.   :    41538   Min.   :13.20  
 1st Qu.:  1605232   1st Qu.:48.23  
 Median :  5570982   Median :53.98  
 Mean   : 12235961   Mean   :54.38  
 3rd Qu.: 13888152   3rd Qu.:60.10  
 Max.   :182201962   Max.   :77.60  
 NA's   :51                         </code></pre>
</div>
</div>
<p>I have confirmed that the above dataset, africa_pop_lifeexp, has 2,907 observations of 2 variables.</p>
<p>I will now plot life expectancy as a function of infant mortality. I expect to see a negative correlation between infant mortality and life expectancy.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot life expectancy as a function of infant mortality        </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(africa_infantmort_lifeexp, <span class="fu">aes</span>(<span class="at">x =</span> infant_mortality, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">labs</span>(</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Life Expectancy vs Infant Mortality in Africa"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">"Infant Mortality"</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">y =</span> <span class="st">"Life Expectancy"</span> </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 226 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="starter-analysis-exercise_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>ggplot() is a function used to initialize a plot object. components must be added using the + operator.</p></li>
<li><p>africa_infantmort_lifeexp is the dataset I want to plot.</p></li>
<li><p>aes() is a function that links data variables to aesthetics, like the x and y position on a graph.</p></li>
<li><p>geom_point() is a function used to add individual points to a plot.</p></li>
<li><p>labs() is a function used to modify various labels of a plot.</p></li>
</ul>
<p>226 rows containing missing values or values outside of the scale range were removed.</p>
<p>I have plotted life expectancy as a function of infant mortality. I saw a negative correlation between infant mortality and life expectancy.</p>
<p>I will now plot life expectancy as a function of population size. in this plot, the x-axis will be set to log scale.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot life expectancy as a function of population size</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># set x-axis to log scale          </span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(africa_pop_lifeexp, <span class="fu">aes</span>(<span class="at">x =</span> population, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>     <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>     <span class="fu">labs</span>( </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Life Expectancy vs Population in Africa"</span>, </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">"Population (log scale)"</span>, <span class="at">y =</span> <span class="st">"Life Expectancy"</span> </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>          )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 51 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="starter-analysis-exercise_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>scale_x_log10() is a function that transforms the x-axis of a plot to a base-10 logarithmic scale.</li>
</ul>
<p>51 rows containing missing values or values outside of the scale range were removed.</p>
<p>I have plotted life expectancy as a function of population size. I saw a positive correlation between population size and life expectancy.</p>
<p>In both plots, there are ‘streaks’ of data. I believe that this due to the fact that I am looking at data for each individual country in africa over several decades (1960 - 2016).</p>
<p>As mentioned previously, 226 rows containing missing values or values outside of the scale range were removed from the first plot looking at life expectancy as a function of infant mortality. I will now figure out which years have missing data for infant mortality.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># determine the number of countries that are missing data on infant mortality per year          </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>africadata <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">summarise</span>(<span class="at">missing_infant =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(infant_mortality))) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>     <span class="fu">arrange</span>(year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 57 × 2
    year missing_infant
   &lt;int&gt;          &lt;int&gt;
 1  1960             10
 2  1961             17
 3  1962             16
 4  1963             16
 5  1964             15
 6  1965             14
 7  1966             13
 8  1967             11
 9  1968             11
10  1969              7
# ℹ 47 more rows</code></pre>
</div>
</div>
<ul>
<li><p>africadata is the dataset that will be used.</p></li>
<li><p>group_by() is a function that organizes data into groups. I will group the data by year.</p></li>
<li><p>summarise() is a function that summarizes a dataset into a single value.</p></li>
<li><p>is.na() is a function that identifies missing values in an object. Here, the object is infant_mortality.</p></li>
<li><p>sum() is a function that adds the number of true values. This will count the number of countries in africa that are missing infant data mortality for each year.</p></li>
<li><p>missing_infant is the name given to the column that will store the counts obtained from the sum(…) function.</p></li>
</ul>
<p>I currently only see the first 10 rows. To see the rest, I will first make missing_infant an object, and then print all rows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># see all years</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>missing_by_year <span class="ot">&lt;-</span> africadata <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">summarise</span>(<span class="at">missing_infant =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(infant_mortality))) <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>     <span class="fu">arrange</span>(year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(missing_by_year, <span class="at">n =</span> <span class="cn">Inf</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 57 × 2
    year missing_infant
   &lt;int&gt;          &lt;int&gt;
 1  1960             10
 2  1961             17
 3  1962             16
 4  1963             16
 5  1964             15
 6  1965             14
 7  1966             13
 8  1967             11
 9  1968             11
10  1969              7
11  1970              5
12  1971              6
13  1972              6
14  1973              6
15  1974              5
16  1975              5
17  1976              3
18  1977              3
19  1978              2
20  1979              2
21  1980              1
22  1981              1
23  1982              0
24  1983              0
25  1984              0
26  1985              0
27  1986              0
28  1987              0
29  1988              0
30  1989              0
31  1990              0
32  1991              0
33  1992              0
34  1993              0
35  1994              0
36  1995              0
37  1996              0
38  1997              0
39  1998              0
40  1999              0
41  2000              0
42  2001              0
43  2002              0
44  2003              0
45  2004              0
46  2005              0
47  2006              0
48  2007              0
49  2008              0
50  2009              0
51  2010              0
52  2011              0
53  2012              0
54  2013              0
55  2014              0
56  2015              0
57  2016             51</code></pre>
</div>
</div>
<p>I can see that all countries in Africa reported infant mortality between the years 1982 - 2015. I will now take a look at data from the year 2000 only. I expect to end up with 51 observations and 9 variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use data only from year 2000          </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>africa_yr2000 <span class="ot">&lt;-</span> africadata <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2000</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(africa_yr2000)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   51 obs. of  9 variables:
 $ country         : Factor w/ 185 levels "Albania","Algeria",..: 2 3 18 22 26 27 29 31 32 33 ...
 $ year            : int  2000 2000 2000 2000 2000 2000 2000 2000 2000 2000 ...
 $ infant_mortality: num  33.9 128.3 89.3 52.4 96.2 ...
 $ life_expectancy : num  73.3 52.3 57.2 47.6 52.6 46.7 54.3 68.4 45.3 51.5 ...
 $ fertility       : num  2.51 6.84 5.98 3.41 6.59 7.06 5.62 3.7 5.45 7.35 ...
 $ population      : num  31183658 15058638 6949366 1736579 11607944 ...
 $ gdp             : num  5.48e+10 9.13e+09 2.25e+09 5.63e+09 2.61e+09 ...
 $ continent       : Factor w/ 5 levels "Africa","Americas",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ region          : Factor w/ 22 levels "Australia and New Zealand",..: 11 10 20 17 20 5 10 20 10 10 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(africa_yr2000)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         country        year      infant_mortality life_expectancy
 Algeria     : 1   Min.   :2000   Min.   : 12.30   Min.   :37.60  
 Angola      : 1   1st Qu.:2000   1st Qu.: 60.80   1st Qu.:51.75  
 Benin       : 1   Median :2000   Median : 80.30   Median :54.30  
 Botswana    : 1   Mean   :2000   Mean   : 78.93   Mean   :56.36  
 Burkina Faso: 1   3rd Qu.:2000   3rd Qu.:103.30   3rd Qu.:60.00  
 Burundi     : 1   Max.   :2000   Max.   :143.30   Max.   :75.00  
 (Other)     :45                                                  
   fertility       population             gdp               continent 
 Min.   :1.990   Min.   :    81154   Min.   :2.019e+08   Africa  :51  
 1st Qu.:4.150   1st Qu.:  2304687   1st Qu.:1.274e+09   Americas: 0  
 Median :5.550   Median :  8799165   Median :3.238e+09   Asia    : 0  
 Mean   :5.156   Mean   : 15659800   Mean   :1.155e+10   Europe  : 0  
 3rd Qu.:5.960   3rd Qu.: 17391242   3rd Qu.:8.654e+09   Oceania : 0  
 Max.   :7.730   Max.   :122876723   Max.   :1.329e+11                
                                                                      
                       region  
 Eastern Africa           :16  
 Western Africa           :16  
 Middle Africa            : 8  
 Northern Africa          : 6  
 Southern Africa          : 5  
 Australia and New Zealand: 0  
 (Other)                  : 0  </code></pre>
</div>
</div>
<p>I can see 51 observations of 9 variables. I will now make the same plots as above again, this time for the year 2000. I expect to see a negative correlation between infant mortality and life expectancy.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot life expectancy as function of infant mortality          </span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(africa_yr2000, <span class="fu">aes</span>(<span class="at">x =</span> infant_mortality, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">labs</span>(</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Life Expectancy vs Infant Mortality in Africa (2000)"</span>,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">"Infant Mortality"</span>,</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">y =</span> <span class="st">"Life Expectancy"</span> </span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="starter-analysis-exercise_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I will now make the same plots as above again, this time for the year 2000. I expect to see no noticeable correlation between population size and life expectancy.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot population size as function of life expectancy          </span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(africa_yr2000, <span class="fu">aes</span>(<span class="at">x =</span> population, <span class="at">y =</span> life_expectancy)) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>     <span class="fu">labs</span>(</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Life Expectancy vs Population in Africa (2000)"</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">x =</span> <span class="st">"Population (log scale)"</span>,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">y =</span> <span class="st">"Life Expectancy"</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="starter-analysis-exercise_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I will fit a linear model to this data. I will fit life expectancy as the outcome and infant mortality as the predictor. I will save the result into an object and view the results of this model.</p>
<ul>
<li><p>lm() is a function used to fit linear models.</p></li>
<li><p>The output is on the left-hand side of ~.</p></li>
<li><p>The predictor is on the right-hand side of ~.</p></li>
<li><p>data = africa_yr2000 is the dataset being used. fit1 is the name of the object being created.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit linear model to life expectancy and infant mortality data          </span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_expectancy <span class="sc">~</span> infant_mortality, <span class="at">data =</span> africa_yr2000)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_expectancy ~ infant_mortality, data = africa_yr2000)

Residuals:
     Min       1Q   Median       3Q      Max 
-22.6651  -3.7087   0.9914   4.0408   8.6817 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      71.29331    2.42611  29.386  &lt; 2e-16 ***
infant_mortality -0.18916    0.02869  -6.594 2.83e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.221 on 49 degrees of freedom
Multiple R-squared:  0.4701,    Adjusted R-squared:  0.4593 
F-statistic: 43.48 on 1 and 49 DF,  p-value: 2.826e-08</code></pre>
</div>
</div>
<p>The y-intercept of the regression line is 71.29331. This is the predicted value of life expectancy when infant mortality = 0. The slope is -0.18916. Life expectancy decreases by 0.18916 years with each infant mortality. The slope is statistically significant (p &lt; 0.001). In sum, this means there is a strong negative correlation between infant mortality and life expectancy, with high infant mortality predicting low life expectancy.</p>
<p>I will now repeat with population size as the predictor variable and life expectancy as the outcome.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit linear model to life expectancy and population size          </span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_expectancy <span class="sc">~</span> population, <span class="at">data =</span> africa_yr2000)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_expectancy ~ population, data = africa_yr2000)

Residuals:
    Min      1Q  Median      3Q     Max 
-18.429  -4.602  -2.568   3.800  18.802 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 5.593e+01  1.468e+00  38.097   &lt;2e-16 ***
population  2.756e-08  5.459e-08   0.505    0.616    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.524 on 49 degrees of freedom
Multiple R-squared:  0.005176,  Adjusted R-squared:  -0.01513 
F-statistic: 0.2549 on 1 and 49 DF,  p-value: 0.6159</code></pre>
</div>
</div>
<p>The y-intercept of the regression line is 55.93. This is the predicted value of life expectancy when population = 0. The slope is 2.756e-08. Life expectancy increases by 2.756e-08 years with each additional person. The slope is not statistically significant. Put together, this means that population size is not a predictor of life expectancy in the year 2000 for countries in Africa.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This part was contributed by Aylla von Ermland</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dslabs"</span>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"pheatmap"</span>)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Load dataset</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"tissue_gene_expression"</span>)</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> tissue_gene_expression<span class="sc">$</span>x</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> tissue_gene_expression<span class="sc">$</span>y</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Check structure</span></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(tissue_gene_expression)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ x: num [1:189, 1:500] 9.83 9.63 9.69 9.99 9.58 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:189] "cerebellum_1" "cerebellum_2" "cerebellum_3" "cerebellum_4" ...
  .. ..$ : chr [1:500] "MAML1" "LHPP" "SEPT10" "B3GNT4" ...
 $ y: Factor w/ 7 levels "cerebellum","colon",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(x)                         </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 189 500</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tissue_gene_expression)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Length Class  Mode   
x 94500  -none- numeric
y   189  factor numeric</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#find what are the tissue types</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(y)                          </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>y
 cerebellum       colon endometrium hippocampus      kidney       liver 
         38          34          15          31          39          26 
   placenta 
          6 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first 10 rows (samples) of the expression matrix to have an idea how the data looks like:</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tissue_gene_expression<span class="sc">$</span>x, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  MAML1     LHPP   SEPT10   B3GNT4  ZNF280D    SOX12 C21orf62
cerebellum_1   9.825680 8.327163 5.499382 8.692371 5.642305 6.254751 5.840938
cerebellum_2   9.631247 8.542827 5.644292 8.833679 5.685083 6.289460 6.065646
cerebellum_3   9.690548 8.476486 5.717187 8.498623 5.958232 6.215924 5.771117
cerebellum_4   9.991592 8.506430 5.789430 8.421143 5.736563 6.512055 5.851617
cerebellum_5   9.578130 8.371783 5.779698 8.818455 5.630886 6.201556 5.965732
cerebellum_6   9.860121 8.278559 5.718611 8.728139 5.708949 6.367384 5.769961
cerebellum_7   9.773119 8.429068 5.833339 8.641901 6.316711 6.251236 5.904653
cerebellum_8   9.683163 8.544539 5.635356 8.810830 5.867560 6.368056 5.925835
cerebellum_9   9.989940 9.350519 6.873389 8.846305 5.749636 6.326722 5.828319
cerebellum_10 10.375016 8.893877 5.920607 8.707563 5.525131 6.616960 5.733619
                  PER3   HOXA10    HOXC5    BLVRB     ZIM2    HEMK1      FAP
cerebellum_1  8.330565 5.520803 7.660495 7.669237 8.355588 7.336959 6.255661
cerebellum_2  8.263576 5.528077 7.569041 7.779377 8.647475 7.282120 6.382161
cerebellum_3  9.102294 5.599405 7.418460 7.552049 8.853757 7.235601 6.124687
cerebellum_4  9.210058 5.561197 7.332254 7.839703 8.202195 7.206341 6.275629
cerebellum_5  8.502172 5.601099 7.535668 7.598154 8.583114 7.530148 6.344579
cerebellum_6  8.766777 5.681404 7.535398 7.720602 8.917125 7.380461 6.163775
cerebellum_7  9.347572 5.554998 7.377026 7.808214 8.873113 7.302264 6.074489
cerebellum_8  8.303106 5.702986 7.468757 7.914037 8.245058 7.493227 6.226500
cerebellum_9  8.735844 5.532744 7.337115 7.797350 8.147067 7.382768 5.961671
cerebellum_10 7.236387 5.958967 7.314246 8.049486 8.528420 7.653198 6.017743
                MAN1A1      CDA   HTR7P1   DALRD3     FIBP   TTTY15  SLC30A1
cerebellum_1  5.331873 6.187845 5.118211 6.338528 9.633268 5.706095 7.815593
cerebellum_2  5.265317 6.199056 5.152341 6.285045 9.935841 6.407302 8.434786
cerebellum_3  5.513315 5.988042 4.975300 6.273408 9.812801 6.529686 8.270430
cerebellum_4  5.334489 5.822462 4.864119 6.641625 9.746305 6.442766 8.619208
cerebellum_5  5.328818 6.022037 5.105351 6.119568 9.584775 5.786363 8.299846
cerebellum_6  5.287141 5.988933 4.975304 6.458174 9.785387 6.636867 7.970605
cerebellum_7  5.377645 5.926435 4.947055 6.476076 9.736893 6.453810 8.357155
cerebellum_8  5.260675 6.163475 5.192956 6.130421 9.735074 6.686859 8.835788
cerebellum_9  5.384552 5.917901 4.982928 6.428380 9.303023 5.558873 8.760358
cerebellum_10 5.195405 6.228623 5.032834 6.582127 9.393906 5.738656 8.742017
                SHANK2     MSL2    UBOX5   DUSP13     GJB5     MTF2   PPP1CA
cerebellum_1  8.055100 7.731915 8.886937 7.195118 6.625296 9.615991 8.663898
cerebellum_2  8.339430 8.103611 8.982832 7.142433 6.459781 9.566402 9.053192
cerebellum_3  8.576553 7.721353 8.642310 7.075302 6.465780 9.669439 8.643137
cerebellum_4  8.587653 7.921687 8.691421 6.990539 6.371063 9.478717 8.811758
cerebellum_5  8.614090 7.550639 8.828745 7.098207 6.264251 9.523913 8.614094
cerebellum_6  8.202925 7.379677 8.782452 7.057468 6.206946 9.244635 8.512298
cerebellum_7  8.162387 8.012479 8.547112 6.996550 6.404973 9.595110 8.662570
cerebellum_8  8.329872 7.817446 8.887676 7.138295 6.422923 9.666881 8.878682
cerebellum_9  8.448657 8.110203 8.850279 6.983031 6.402117 9.324518 8.602517
cerebellum_10 8.726472 8.057855 8.864391 6.866285 6.572482 9.114295 8.823426
               IGHMBP2    VEGFA  KANSL1L     FCN3   USP32P2   HIVEP3     HRH1
cerebellum_1  7.106520 8.739896 5.456000 6.629619  9.963952 7.930915 5.909219
cerebellum_2  7.179572 9.104418 5.412921 6.474211 10.059571 7.930661 6.151618
cerebellum_3  7.182513 8.124053 5.538408 6.586115 10.650234 7.887439 5.827940
cerebellum_4  7.235387 8.819885 5.473543 6.653342 10.286083 7.715903 5.790850
cerebellum_5  7.170698 9.139441 5.397045 6.732249  9.789580 7.857671 5.909583
cerebellum_6  7.154251 8.469904 5.306231 6.893714 10.248553 8.031649 5.776629
cerebellum_7  7.176363 8.433903 5.407979 6.968214 10.865818 7.842132 5.645728
cerebellum_8  7.013573 8.558452 5.296812 6.432282  9.892678 7.871021 5.922232
cerebellum_9  6.974503 8.649570 5.256353 6.678192 10.233516 7.827576 5.733902
cerebellum_10 7.308843 9.568389 5.293391 6.893504  9.914499 7.364454 5.656550
                 HDAC7      HTT    IDH3A     TLR3     F11R     MOAP1    ISOC2
cerebellum_1  8.101766 8.387363 7.919697 5.219807 7.702429 10.563195 8.025057
cerebellum_2  8.203845 8.181833 7.784183 5.264430 7.777864 10.547947 8.205154
cerebellum_3  8.049845 8.139918 8.866420 5.192569 7.395236 11.050301 7.798635
cerebellum_4  8.362647 8.221108 8.011794 5.278299 7.415947 10.705730 7.978353
cerebellum_5  7.797651 8.340593 7.993639 5.233093 7.245353 10.724983 7.962394
cerebellum_6  8.326631 8.325037 8.540433 5.319939 7.382185 10.883654 7.829789
cerebellum_7  8.159347 8.363103 8.817934 5.250205 7.152414 10.894981 7.837663
cerebellum_8  7.846576 8.302566 7.840592 5.254624 7.616637 10.565182 8.058362
cerebellum_9  7.919670 8.256456 8.020326 5.221364 7.416600 10.528014 7.978839
cerebellum_10 9.009654 8.170810 7.122072 5.222194 7.508849  9.886291 8.048327
                 CLIP3    FZD10     VOPP1     RPL4    NUDT2    RAB30      DBI
cerebellum_1  11.71842 5.970661  9.402392 11.95729 7.265705 6.866061 10.73213
cerebellum_2  12.05089 6.086282  9.665320 11.74977 7.128560 6.895061 11.55146
cerebellum_3  11.78952 5.881767  9.900131 11.81548 7.094722 6.828293 11.43216
cerebellum_4  12.00438 6.009886  9.853845 11.87613 7.178623 6.583045 12.04055
cerebellum_5  11.77537 5.733106  9.326293 11.92530 7.204355 6.772551 11.43846
cerebellum_6  11.78114 5.968254  9.736839 11.62525 7.272790 6.580270 11.58310
cerebellum_7  11.82003 5.802794 10.077973 11.90911 6.914814 6.777572 10.79858
cerebellum_8  11.80804 6.011812  9.564617 11.87315 7.151676 7.006499 11.95236
cerebellum_9  11.69210 5.820063  9.632840 11.86429 7.090901 6.711875 11.85175
cerebellum_10 12.08421 5.859303  9.942251 11.97767 6.954811 6.811375 12.04865
                CCDC87  GALNT11    APBA1    IGF2R    GNG13    KCNE4    CETN2
cerebellum_1  6.750286 8.937617 8.273928 6.769386 8.345475 5.485829 7.836339
cerebellum_2  6.874440 8.932414 8.305099 6.931467 8.535819 5.538835 8.120701
cerebellum_3  6.872545 9.127671 8.249492 6.959763 8.525109 5.506407 8.141291
cerebellum_4  6.650082 9.417260 8.118530 7.115318 7.895336 5.500762 8.586232
cerebellum_5  6.698553 9.141660 8.324606 7.050973 8.848026 5.304758 8.019902
cerebellum_6  6.781381 8.907533 8.686231 6.949713 7.361954 5.361314 8.193473
cerebellum_7  6.706252 9.380676 8.315357 6.916564 8.085471 5.357100 8.007685
cerebellum_8  6.607022 9.144236 8.295219 7.126795 8.259925 5.432546 8.151796
cerebellum_9  6.708731 8.924885 8.217046 7.132280 8.205528 5.485036 8.314260
cerebellum_10 6.735856 9.393873 8.012087 6.960170 7.679726 5.590611 8.484144
                OR7A17     CINP     AQP7    CFHR4   EXOC6B   NDUFS4    GALK2
cerebellum_1  5.713501 5.203313 7.928875 5.455091 5.148188 8.875961 6.241525
cerebellum_2  5.790924 5.181507 7.835421 5.433896 5.009589 8.950426 5.953925
cerebellum_3  5.782477 5.184345 7.888749 5.386960 5.067368 9.423109 6.149192
cerebellum_4  5.901639 5.206621 7.635983 5.556088 5.076868 9.103697 5.948905
cerebellum_5  5.693372 5.249499 7.929188 5.469491 5.065496 9.062430 6.258561
cerebellum_6  5.872933 5.337801 8.166138 5.467245 5.062163 9.076375 6.010717
cerebellum_7  5.572556 5.174997 8.096925 5.241946 5.070176 9.516976 6.155411
cerebellum_8  5.673692 5.257544 7.596216 5.397847 5.165453 8.819811 6.204298
cerebellum_9  5.729613 5.354502 8.057736 5.344007 5.161729 8.991999 6.153022
cerebellum_10 5.680367 5.049670 7.532695 5.408501 5.082562 8.635461 5.990772
                 NTSR2    RPS16   FAM30A      RRH  RPS6KA3    CERKL    RSRP1
cerebellum_1  7.627295 11.65408 6.700581 6.074728 7.588707 5.461044 8.387013
cerebellum_2  8.156978 11.19379 6.689519 6.219099 7.785763 5.574510 7.769011
cerebellum_3  7.388339 11.22438 6.604070 6.134798 7.888876 5.521763 8.423310
cerebellum_4  8.158031 11.38917 6.466977 5.831856 7.479554 5.332587 8.974699
cerebellum_5  8.118178 11.29670 6.525788 5.993254 7.730904 5.695885 8.632062
cerebellum_6  7.599206 11.36751 7.044216 6.132831 7.266692 5.579746 8.328103
cerebellum_7  7.422699 11.38996 6.618160 6.000181 7.607352 5.527634 9.064462
cerebellum_8  8.175541 11.27009 6.647917 5.906307 7.883631 5.493337 8.388592
cerebellum_9  8.280382 11.91183 6.375491 5.917457 7.409876 5.307018 8.236698
cerebellum_10 8.306913 11.41859 6.586863 6.005961 7.248444 5.413562 7.676567
                 H2AFY     SMTN   GPR171    ENPEP     ALX4     POLL   SEMA4A
cerebellum_1  11.37612 7.517958 5.450099 4.698821 6.396912 7.902547 9.324884
cerebellum_2  11.35739 8.369050 5.460365 4.738336 6.476127 8.003341 9.214846
cerebellum_3  11.44971 7.839224 5.418038 4.759188 6.244648 7.726691 8.704265
cerebellum_4  11.45595 8.266981 5.394933 4.780322 6.176294 7.931901 8.785098
cerebellum_5  11.06885 8.178817 5.337093 4.802553 6.347351 7.713012 8.988912
cerebellum_6  11.53450 7.950101 5.511447 4.669933 6.035575 7.833934 8.899724
cerebellum_7  11.44250 7.363635 5.376697 4.841929 6.123742 7.832061 8.674825
cerebellum_8  11.26575 7.890585 5.541595 4.777836 6.376310 7.812357 9.239734
cerebellum_9  11.11732 8.177632 5.442821 4.795344 6.163794 7.744530 8.866450
cerebellum_10 11.36004 8.642768 5.470237 4.864972 6.276702 7.947876 9.240268
              PAFAH1B2    LRRN3    HNF1A   SREBF2    NARS2    TACC3   GALNT2
cerebellum_1  6.882600 9.041457 7.729246 9.396224 8.311774 6.156942 5.235970
cerebellum_2  6.944754 8.385604 7.491146 9.366962 8.109466 6.462386 5.109273
cerebellum_3  6.848901 8.499926 7.435543 9.569892 8.270311 6.124352 5.148484
cerebellum_4  6.825181 8.694849 7.480627 9.644535 8.155522 6.067010 5.059927
cerebellum_5  6.880359 8.545008 7.611682 8.893966 8.009478 6.329258 5.158726
cerebellum_6  7.050896 8.180885 7.283383 9.517017 7.840651 6.265199 5.303118
cerebellum_7  6.932712 8.676777 7.473797 9.485840 8.229675 6.362416 5.281459
cerebellum_8  6.931505 8.694497 7.542228 9.408727 8.011683 6.216533 5.271094
cerebellum_9  6.904578 8.379750 7.368275 9.061947 8.204599 6.298099 5.404607
cerebellum_10 7.054314 8.538690 7.692907 9.261550 7.967801 6.222311 5.086504
                VPS13A   ZNF552    PA2G4     OAZ3     CD14  SLC38A2    HDAC3
cerebellum_1  8.285018 7.026912 8.723233 5.898497 7.675994 10.07744 8.813273
cerebellum_2  7.898175 7.066586 8.761516 6.072404 6.847956 10.13586 8.998637
cerebellum_3  8.133022 6.873660 8.820185 5.967411 7.794195 10.93926 8.932150
cerebellum_4  8.044855 6.746749 8.981604 6.002854 7.147262 10.45045 8.928942
cerebellum_5  8.622143 7.222091 8.713719 5.864352 6.666781 10.38068 8.857360
cerebellum_6  8.467834 6.945969 8.942579 5.984682 7.070005 10.85592 9.006563
cerebellum_7  8.215846 6.828568 8.806419 5.863734 7.044708 10.90860 8.880386
cerebellum_8  8.190974 7.186801 8.682320 5.944240 7.077881 10.77308 8.814344
cerebellum_9  7.984900 6.997460 8.803749 5.804376 6.660182 10.57438 8.726606
cerebellum_10 7.904735 6.718424 9.024117 5.869642 6.932254 10.34615 8.844891
                 SPIDR    DKKL1    DDX49      KIN  SLC6A11      GIP   CARD10
cerebellum_1  5.159590 7.056522 5.476065 5.213787 6.581743 5.496049 7.576163
cerebellum_2  5.105660 7.239378 5.492753 5.338877 6.597096 5.381804 7.763525
cerebellum_3  5.061804 6.849455 5.550662 5.616978 6.426169 5.352301 7.505631
cerebellum_4  5.048114 7.072436 5.575075 5.558047 6.423822 5.476271 7.475320
cerebellum_5  5.029570 6.973183 5.459293 5.370379 6.537187 5.410118 7.746978
cerebellum_6  5.014261 6.905785 5.351596 5.410996 6.545775 5.490850 7.714652
cerebellum_7  5.134978 6.931424 5.513477 5.327155 6.554397 5.431669 7.738744
cerebellum_8  5.037033 6.976662 5.547758 5.519313 6.675955 5.458482 7.604621
cerebellum_9  5.098413 6.810485 5.718440 5.417746 6.538848 5.414897 7.417077
cerebellum_10 5.032208 7.370454 5.787448 5.330113 6.871363 5.415821 8.182651
                  SUSD6 LINC01361   PHLDB1     SPCS1     INF2   MAN1A2   CELSR2
cerebellum_1  10.418700  5.021649 8.711464  9.603325 7.440754 5.661723 8.923354
cerebellum_2   9.791382  5.054141 8.684584  9.656491 7.478873 5.758106 8.997941
cerebellum_3  10.357840  4.942724 8.486951 10.144990 7.243743 5.643627 9.198864
cerebellum_4  10.840044  5.101968 8.748248 10.150642 7.326476 5.680170 9.279997
cerebellum_5  10.426138  5.011961 8.445128  9.857244 7.405117 5.673409 9.047094
cerebellum_6  10.548582  4.994960 8.476534 10.319307 7.420393 6.124349 8.874260
cerebellum_7  10.261810  4.979198 8.616549 10.116569 7.403890 5.662254 9.254924
cerebellum_8  10.480672  5.009862 8.300568  9.951007 7.326776 5.823984 9.169630
cerebellum_9  10.414865  5.052346 8.796187 10.072550 7.505921 5.611940 9.050196
cerebellum_10 10.211794  5.119906 9.104217  9.610866 7.592562 5.707008 9.294978
                COL1A2     UBR2    CCL21     DMWD    KRIT1    DDAH2  SLC25A5
cerebellum_1  7.067175 7.411077 6.710379 7.317716 7.629896 7.263812 10.80736
cerebellum_2  7.644435 7.311405 7.080759 7.361764 7.416533 7.991669 11.00119
cerebellum_3  7.317476 7.283485 6.720008 7.262095 7.245429 7.677090 11.52201
cerebellum_4  7.224327 7.529148 6.722679 7.173691 7.415799 7.858066 11.19765
cerebellum_5  6.996878 7.524035 6.527712 7.432770 7.389222 7.092030 10.64970
cerebellum_6  7.259418 7.680524 6.728924 7.315659 7.629221 7.816167 11.17989
cerebellum_7  7.366479 7.354621 6.665258 7.219981 7.618812 7.594044 11.40073
cerebellum_8  7.112425 7.450017 6.598682 7.282642 7.469257 7.842401 10.79987
cerebellum_9  6.947828 7.538014 6.725270 7.278023 7.438448 7.954284 10.71120
cerebellum_10 7.263531 7.306544 6.797782 7.661150 7.710871 7.868087 10.64046
                 PPME1    OPHN1      MPZ   PRDM14   ZC3H7B   NECAB3    UBE3B
cerebellum_1  9.443002 11.51590 7.540403 7.826045 7.567918 7.540004 8.205530
cerebellum_2  9.736270 11.25634 7.521132 7.655382 7.728090 7.744704 8.312074
cerebellum_3  9.641149 11.38279 7.270481 7.557272 7.436655 7.719730 8.241914
cerebellum_4  9.605028 11.17579 7.384934 7.525903 7.595224 7.605689 8.528242
cerebellum_5  9.411285 11.58267 7.264692 7.625392 7.619645 7.511907 8.349906
cerebellum_6  9.569169 11.52552 7.606375 7.907554 7.743443 7.587195 7.876897
cerebellum_7  9.634548 11.39989 7.187461 7.637902 7.643244 7.896415 8.365351
cerebellum_8  9.444884 11.51886 7.428702 7.533243 7.669668 7.496696 8.316041
cerebellum_9  9.411571 11.50578 7.303844 7.456451 7.635452 7.552213 8.357188
cerebellum_10 9.868383 10.70779 7.676848 7.835781 7.737391 7.764105 8.471115
                ZNF529   CRYBA2   CCDC86   SNAPC3    DDX31 PRELID3A    RPE65
cerebellum_1  7.828406 5.705068 8.589090 7.299060 8.702716 6.503070 4.358204
cerebellum_2  6.854627 5.659492 8.652727 7.090648 8.635400 6.538479 4.478693
cerebellum_3  7.823043 5.469643 8.535615 7.315794 8.549825 6.331826 4.378901
cerebellum_4  8.146521 5.597409 8.551529 7.147951 8.407500 6.417461 4.381484
cerebellum_5  7.362238 5.348489 8.887649 7.404311 8.576810 6.458225 4.391113
cerebellum_6  7.734804 5.457911 8.633179 7.809627 8.743987 6.471212 4.438545
cerebellum_7  7.794946 5.484531 8.720230 7.145301 8.483162 6.374972 4.416876
cerebellum_8  7.540995 5.449982 8.768522 7.072583 8.487735 6.651570 4.354361
cerebellum_9  7.309150 5.487723 8.801428 7.436794 8.397542 6.408879 4.386607
cerebellum_10 7.227496 5.670167 8.479795 6.905953 8.515375 6.415833 4.444995
                ZC3H13   IL18R1    SREK1      AK4    VPS51     BTG4     SDHB
cerebellum_1  7.357710 5.357987 8.239860 6.771812 10.79653 6.090793 8.176924
cerebellum_2  7.298097 5.661605 8.547656 6.499894 10.63359 6.083282 8.354722
cerebellum_3  6.977849 5.480377 8.488367 7.077391 10.57767 6.246317 8.571798
cerebellum_4  7.168155 5.349079 8.418649 6.541867 10.67968 6.018993 8.251907
cerebellum_5  6.636035 5.282220 8.471203 6.752738 10.73521 5.933669 7.866181
cerebellum_6  6.912556 5.488540 8.770232 6.823932 10.25143 6.071453 8.506839
cerebellum_7  6.678148 5.370589 8.627881 6.916751 10.72698 6.151286 8.455661
cerebellum_8  6.896883 5.317712 8.421612 6.639163 10.63867 5.977247 8.688314
cerebellum_9  7.006279 5.324711 8.842181 6.536607 10.40882 6.290632 8.167673
cerebellum_10 6.554443 5.547982 8.192369 5.980767 10.78222 6.360833 7.940855
               EFCAB14     KCTD2      NDP TMEM185B   NUDT11  KIR2DL2   UQCRC2
cerebellum_1  9.480229 10.131302 6.915502 5.181354 8.531076 7.388890 9.383569
cerebellum_2  9.462271 10.270619 7.247328 5.182788 8.743157 7.245897 9.295328
cerebellum_3  9.185483 10.445814 6.659822 5.264065 8.388127 7.444212 9.929172
cerebellum_4  9.197386 10.299107 7.747937 5.330668 8.305869 7.468625 9.311786
cerebellum_5  9.402280 10.363449 6.365040 5.138203 8.522833 7.311529 9.485599
cerebellum_6  9.147101 10.488714 6.777785 5.386571 8.333299 7.523343 9.655585
cerebellum_7  9.216713 10.214294 7.544402 5.261323 8.244465 7.359023 9.803480
cerebellum_8  9.501117 10.514180 6.936508 5.386510 8.309042 7.429481 9.485163
cerebellum_9  9.465162 10.088418 7.576083 5.494910 7.991005 7.399910 9.400925
cerebellum_10 9.025091  9.994595 6.094826 5.400305 8.181325 7.558862 8.751471
                 MPRIP  SLC16A4     PRR7   COL9A1    VEGFC      GAK    NR0B1
cerebellum_1  10.47643 4.521262 6.067429 6.845894 5.897006 5.719498 4.897821
cerebellum_2  10.64491 4.654505 6.367330 6.791721 6.049724 5.902940 4.776398
cerebellum_3  11.03402 4.552808 5.862647 6.747800 5.762470 5.760897 4.889299
cerebellum_4  10.71920 4.601510 6.106998 6.673721 5.630897 5.664206 4.869762
cerebellum_5  10.56419 4.568961 5.960051 6.813671 6.045302 5.852671 4.893827
cerebellum_6  10.65116 4.555073 6.259022 6.677552 5.665779 5.706984 4.885830
cerebellum_7  10.83684 4.612479 6.055619 6.536991 5.645057 5.573447 4.900470
cerebellum_8  10.29751 4.670575 6.079781 6.704843 5.886228 5.743129 4.839823
cerebellum_9  10.58363 4.604382 6.178367 6.581693 5.983462 5.540426 4.872299
cerebellum_10 11.07636 4.615668 6.569026 6.789908 5.957792 5.722720 5.047126
               TMEM104   FER1L4    RPS11 LINC01711 C1orf112     MYL7 LOC643733
cerebellum_1  7.782577 5.206248 13.18198  6.742105 5.296176 7.171815  4.983906
cerebellum_2  7.743475 5.106888 13.17524  6.822944 5.228125 7.007831  4.937063
cerebellum_3  7.374634 5.068150 13.13042  6.708040 5.251990 7.080141  4.904283
cerebellum_4  7.565507 5.026098 13.21040  6.720816 5.323897 7.161795  4.897315
cerebellum_5  7.597987 5.267973 13.22074  6.688955 5.204844 6.829463  5.040929
cerebellum_6  7.613566 5.181412 13.15728  6.693197 5.295898 6.995367  4.890654
cerebellum_7  7.637702 5.170805 13.01294  6.691062 5.210214 7.032964  4.968116
cerebellum_8  7.472306 5.251842 13.20576  6.742644 5.140827 7.064980  4.935121
cerebellum_9  7.501219 5.059055 13.23708  6.541440 5.280640 6.919640  4.979836
cerebellum_10 7.972655 5.341046 13.19748  6.728843 5.078118 7.660261  4.869450
                SAPCD1  HSPBAP1    GNA11   FKBP1B   TICAM1    GSK3B    UBE2O
cerebellum_1  6.700761 6.269026 10.19026 8.936448 5.833524 8.040857 8.494453
cerebellum_2  7.302202 6.178615 10.13841 8.976958 6.157176 8.147178 8.569545
cerebellum_3  7.001034 6.160917 10.13726 9.333116 5.887706 8.578211 8.258800
cerebellum_4  6.685868 6.205609 10.28766 9.690465 5.959711 8.999048 8.522814
cerebellum_5  7.084984 6.197007 10.14897 9.044336 6.090392 8.183766 8.595739
cerebellum_6  6.759533 5.823401 10.28454 9.063804 6.105232 8.600974 8.423246
cerebellum_7  6.924631 6.197925 10.24409 9.683336 6.171088 8.742989 8.407894
cerebellum_8  6.611828 6.020362 10.16743 9.094075 6.032561 8.016373 8.548945
cerebellum_9  6.463591 6.300358 10.02079 9.145157 6.253177 8.485344 8.437888
cerebellum_10 7.033027 6.481302 10.46837 9.173379 6.292294 8.237254 8.745184
                  AFDN   TICAM2     PSMG2     BAGE     OAZ1 TMEM184B    WWTR1
cerebellum_1  5.082258 6.128732 10.208667 4.483442 12.82831 8.811363 6.682000
cerebellum_2  5.183993 5.718105  9.675275 4.424610 12.86871 8.858422 6.959622
cerebellum_3  5.047976 5.856607 10.028249 4.394252 12.83233 9.059709 6.923787
cerebellum_4  5.133987 6.114305 10.340812 4.452152 12.89368 9.214730 6.625300
cerebellum_5  5.062199 5.854132  9.934572 4.481915 12.78003 8.833165 6.404537
cerebellum_6  5.118202 5.865037  9.763917 4.485098 12.99567 9.040673 6.883767
cerebellum_7  5.213353 6.002703  9.932084 4.544008 12.94025 9.033436 6.674695
cerebellum_8  5.140321 5.924890 10.175941 4.423539 12.74874 8.722111 6.997479
cerebellum_9  5.180092 5.940905 10.131235 4.520324 12.80751 9.273375 6.730456
cerebellum_10 5.050082 5.689660 10.196185 4.600170 12.89109 9.151295 6.765140
                 HHLA1   LGALSL   LRRC36  ARHGEF5    TESK2    PTPRO  FAM184A
cerebellum_1  8.965772 7.177295 6.599195 8.232152 8.900686 6.091161 8.691674
cerebellum_2  9.066358 7.413692 6.608489 7.914311 8.766186 5.943494 8.441254
cerebellum_3  8.909074 7.286206 6.548764 7.891672 8.635427 6.132684 8.625112
cerebellum_4  8.813343 7.175834 6.548812 7.796217 8.643978 6.081096 8.609687
cerebellum_5  9.003465 7.396820 6.493376 8.083094 8.972774 6.244904 8.671549
cerebellum_6  9.219278 7.472773 6.682370 8.022962 9.069412 6.100650 8.173491
cerebellum_7  9.015159 7.244080 6.488262 7.763087 8.415196 6.013073 8.621151
cerebellum_8  9.031463 7.411758 6.479681 8.079026 8.802907 6.015681 8.835348
cerebellum_9  8.904825 7.367041 6.541349 7.781586 8.813430 5.852891 8.576142
cerebellum_10 8.975515 7.408633 6.823127 7.847433 8.216607 5.703164 8.696246
                 PLCB1  PLEKHO1      NBN APOBEC3B   ZBTB22     LSM1   KLRA1P
cerebellum_1  4.992272 8.278359 7.455471 5.170419 7.887351 9.070975 4.884114
cerebellum_2  4.812346 8.795685 7.391464 5.087435 8.232794 9.420614 4.881206
cerebellum_3  5.025941 8.364655 7.611050 5.025135 7.999299 9.552306 4.867865
cerebellum_4  4.913295 8.674028 7.665825 4.952644 8.068554 9.484452 4.849933
cerebellum_5  5.038107 8.356521 7.392223 5.098261 7.869007 9.154832 4.821896
cerebellum_6  5.255558 8.424424 7.347608 5.091690 8.104289 9.063103 4.781701
cerebellum_7  5.078014 8.243962 7.604029 4.955652 8.053031 9.427728 4.805326
cerebellum_8  5.038313 8.386612 7.463526 5.177130 7.849955 9.484716 4.867019
cerebellum_9  5.112888 7.963232 7.669470 4.976402 7.909613 9.285475 4.739780
cerebellum_10 4.925797 8.636868 7.696308 5.116987 8.116850 9.915365 4.776041
                 GPA33     BDH1  EHBP1L1     COPB1 SLC25A37     PBLD    MCPH1
cerebellum_1  7.930732 8.394575 6.146187  9.942229 7.259716 5.992428 6.027278
cerebellum_2  7.943701 8.378980 6.152756 10.115713 6.874231 6.086766 6.010715
cerebellum_3  7.575661 8.279915 5.834283 10.264896 6.816275 6.139485 5.937376
cerebellum_4  7.436592 8.618619 5.946096 10.433977 6.843695 6.099366 5.834794
cerebellum_5  7.946434 8.257173 5.972145 10.040874 7.261113 6.059816 5.802041
cerebellum_6  7.943176 8.498587 6.254275 10.121178 7.104208 6.173777 5.995401
cerebellum_7  7.436591 8.398980 5.983140 10.213614 7.024993 6.068756 6.089661
cerebellum_8  7.942701 8.229997 5.963365 10.048423 7.197566 6.112007 6.114945
cerebellum_9  7.796648 8.266755 6.284667 10.190048 7.209196 6.026247 6.005322
cerebellum_10 7.274348 8.274629 5.945457 10.773553 6.928010 6.082274 5.832225
              LOC155060    MST1L   KCNJ12  PRSS3P2    NAA11     RHOG    PTH2R
cerebellum_1   8.853877 7.994323 9.006811 8.684089 6.806276 9.153160 5.620893
cerebellum_2   8.668308 7.909402 8.339302 8.708898 6.756744 9.066028 5.753220
cerebellum_3   8.639589 7.652136 9.475371 8.394335 6.610608 9.048236 5.599236
cerebellum_4   8.626132 7.823761 9.438423 8.455435 6.422208 8.978894 5.374749
cerebellum_5   8.891979 7.741361 8.866531 8.376845 6.764107 9.173313 5.596001
cerebellum_6   8.800090 7.910758 8.721475 8.773455 6.670323 9.079744 5.425492
cerebellum_7   8.823426 7.574241 8.630908 8.443160 6.456515 9.135360 5.304071
cerebellum_8   8.871277 7.812785 9.161944 8.353100 6.903530 9.076402 5.656720
cerebellum_9   8.725341 7.603656 8.699790 8.414682 6.628427 9.427000 5.420759
cerebellum_10  8.823059 7.775813 8.671158 8.588830 6.458967 9.545696 5.359923
               CYP4F11    ACAA1    SUGP1    FOXD1     IRS4    MUC3A   MBTPS1
cerebellum_1  4.898388 8.558544 8.480330 5.759241 6.401616 7.957608 9.476258
cerebellum_2  5.052523 8.643545 8.259850 5.783693 6.387229 7.606584 9.292767
cerebellum_3  4.874359 8.515528 8.126589 5.300626 6.221108 7.869058 9.425367
cerebellum_4  4.907513 8.742626 8.234357 5.759803 6.067656 7.871909 9.621449
cerebellum_5  4.986159 8.599788 8.306990 5.705443 6.091952 7.883048 9.149824
cerebellum_6  4.997934 8.727885 8.282005 5.571154 6.242612 8.092517 9.305339
cerebellum_7  4.820282 8.670298 8.366391 5.680427 6.233624 7.963908 9.222560
cerebellum_8  4.959952 8.577863 8.138406 5.883863 6.119365 7.723141 9.079743
cerebellum_9  4.869878 8.673023 8.085111 5.710491 6.232787 7.632508 9.343611
cerebellum_10 5.071120 9.117947 7.959150 5.718894 6.649430 7.976775 9.297117
              COLGALT2    PTGFR  KHDRBS1 MAPK8IP3   PTTG1IP   ZNF135    MTMR7
cerebellum_1  7.531142 4.728902 11.41495 8.639891  9.819089 5.298334 5.056329
cerebellum_2  7.703055 4.754562 11.32567 8.789521 10.108370 5.254386 4.897062
cerebellum_3  7.762285 4.711777 11.40307 8.558256 10.028519 5.465984 5.048228
cerebellum_4  7.736560 4.686905 11.46953 8.650876 10.680789 5.218499 4.871457
cerebellum_5  7.348595 4.690572 11.08532 8.498181 10.036272 5.234240 4.998906
cerebellum_6  7.759173 4.760308 11.57651 8.773150 10.132427 5.459650 4.923010
cerebellum_7  7.913645 4.766366 11.46062 8.650913  9.940872 5.261961 4.952686
cerebellum_8  7.641189 4.720641 11.23129 8.437778 10.417820 5.304877 4.946359
cerebellum_9  8.127094 4.698458 11.30988 8.430874 10.680877 5.195162 4.968337
cerebellum_10 7.451382 4.747089 10.89286 9.067795 11.024977 5.273712 5.009255
                  GYPE     RARS    GPM6B   PMFBP1    KLHL9     DRG2      JAK1
cerebellum_1  4.737416 7.875761 11.85945 7.666321 6.731204 8.324930 10.516817
cerebellum_2  4.782874 7.926972 12.66113 7.896839 6.555759 8.455055  9.903277
cerebellum_3  4.688485 8.017281 12.58120 7.811519 6.560779 8.409612 10.389982
cerebellum_4  4.685529 7.960191 12.83616 7.587842 6.527081 8.421128 10.123318
cerebellum_5  4.764033 8.140422 12.50615 7.870173 6.358885 8.039340 10.195624
cerebellum_6  4.739754 7.781746 12.52523 7.657513 6.367527 8.362700 10.592673
cerebellum_7  4.704029 8.089983 11.91415 7.590639 6.509713 8.290148 10.566561
cerebellum_8  4.721138 8.373744 12.73582 8.140764 6.345938 8.415094 10.132867
cerebellum_9  4.776634 7.836820 13.24142 7.803945 6.731751 8.456587 10.370432
cerebellum_10 4.600464 7.668130 12.99100 7.467495 6.465843 8.691454  9.696645
                  TFR2     NCOR1  IL12RB1   COL6A3   CLDN10   GVINP1      EVC
cerebellum_1  5.618901  9.375796 7.319110 6.397518 7.155621 6.791130 7.538936
cerebellum_2  5.552897  9.311354 7.297188 6.482381 8.086663 6.653781 7.708866
cerebellum_3  5.477241  9.571846 7.177052 6.280237 7.472417 6.439030 7.442824
cerebellum_4  5.642026  9.822920 7.005666 6.285309 8.034690 6.508993 7.558361
cerebellum_5  5.516667  9.364262 7.338864 6.461578 7.433706 6.737157 7.616201
cerebellum_6  5.559028  9.492255 7.082468 6.580389 7.959668 6.653167 7.713795
cerebellum_7  5.627233  9.755179 7.109878 6.285711 7.099813 6.598784 7.572621
cerebellum_8  5.583512  9.462741 7.259553 6.252454 8.229485 6.677960 7.586585
cerebellum_9  5.558374  9.660348 7.236184 5.972840 7.821874 6.584284 7.567275
cerebellum_10 5.603168 10.040279 7.082072 6.317305 7.936929 6.486414 7.738552
               TNFAIP2   SAMD4B     TSFM     UBE3A  COL4A3BP   FCGR3B   ATXN3L
cerebellum_1  7.775709 7.598732 8.914851  9.626137 10.257996 6.968990 5.371557
cerebellum_2  7.983357 7.421354 8.820335  9.430119  9.980541 5.737047 5.607838
cerebellum_3  7.681563 7.402856 8.670402 10.014743 10.062872 5.942066 5.341153
cerebellum_4  7.482706 7.338207 8.830121  9.964598 10.523813 5.823224 5.274275
cerebellum_5  7.655897 7.623423 8.708332  9.723745 10.334536 5.956962 5.261478
cerebellum_6  7.752794 7.374944 8.868752  9.548427 10.561466 5.952295 5.375671
cerebellum_7  7.609848 7.386576 8.608204  9.726226 10.157187 5.605999 5.267605
cerebellum_8  7.753588 7.529173 8.780435  9.846465 10.453354 5.937997 5.397909
cerebellum_9  7.532804 7.267844 8.703270  9.403803 10.251608 5.763767 5.411201
cerebellum_10 7.836346 7.465238 8.603950 10.212525 10.418514 5.615853 5.372553
                  RAC2  ANAPC15  RARRES2 ATP6V0A2    SARDH  TBC1D16     AATF
cerebellum_1  6.212297 8.236687 7.342078 5.206413 5.615891 8.903363 8.929525
cerebellum_2  6.162151 8.395634 7.828041 5.251039 5.492792 8.716464 9.170989
cerebellum_3  6.083827 8.273269 7.266519 5.367502 5.603600 8.762927 8.866088
cerebellum_4  6.060047 8.084226 7.359143 5.265789 5.517324 9.377328 9.172039
cerebellum_5  5.926534 8.511706 7.148505 5.080795 5.484533 8.854246 8.918395
cerebellum_6  6.038377 8.046575 7.253235 5.374858 5.558658 8.906275 8.480529
cerebellum_7  5.935075 8.321635 7.235061 5.236657 5.340730 8.791592 8.844143
cerebellum_8  5.993871 8.427544 7.450365 5.213907 5.530030 8.551290 8.944022
cerebellum_9  6.028988 8.256209 7.385565 5.232786 5.490999 8.974220 9.084538
cerebellum_10 6.022280 8.225970 7.761993 5.114568 5.477156 9.318201 9.230837
                CHCHD3    CASP9    BMP8B    CAPN3    MCTP2     SV2B   RNF123
cerebellum_1  7.822421 8.370530 5.836588 8.047982 6.415642 11.30951 9.341797
cerebellum_2  7.835211 8.684662 5.868453 7.676551 6.560079 11.16642 9.348351
cerebellum_3  8.151315 8.325787 5.499581 7.743128 6.150426 11.58975 9.151590
cerebellum_4  8.006660 8.621397 5.498825 7.864190 6.127522 11.08582 9.173076
cerebellum_5  7.818410 8.338811 5.713007 8.275358 6.556660 11.33622 9.334195
cerebellum_6  7.915906 8.329450 5.589067 7.765812 6.325589 11.38062 9.125707
cerebellum_7  8.062459 8.604781 5.493694 8.216493 6.029919 11.21015 8.982978
cerebellum_8  7.861468 8.397144 5.698793 8.385040 6.179022 11.28399 9.411929
cerebellum_9  7.893576 8.516375 5.606737 9.319236 6.127783 11.02281 8.998962
cerebellum_10 7.810756 8.726842 5.598327 8.087623 5.813583 11.07627 9.345885
                  BCL3     RFNG    IKZF1     RPL3    MATN3    SAGE1     FLI1
cerebellum_1  7.281782 8.584903 7.020103 13.53170 4.309015 5.133167 5.134625
cerebellum_2  7.382006 8.652015 7.041422 13.49961 4.366581 5.190883 4.880506
cerebellum_3  7.002148 8.320944 6.728308 13.55254 4.341674 5.218103 4.919040
cerebellum_4  7.006433 8.690087 6.725977 13.51249 4.329932 5.127260 5.155668
cerebellum_5  7.260650 8.402169 7.199936 13.60050 4.371580 5.121351 4.916079
cerebellum_6  7.079558 8.800068 6.840323 13.65830 4.310329 5.169811 4.945050
cerebellum_7  6.950604 8.494048 6.741813 13.74562 4.347345 5.232479 4.915298
cerebellum_8  7.206807 8.418767 7.118150 13.46060 4.279047 5.109162 5.011030
cerebellum_9  6.933538 8.588074 6.737204 13.59142 4.331087 5.275193 5.043126
cerebellum_10 7.213072 8.537987 6.863298 13.31960 4.366674 5.167550 5.226220
                 AGAP1     TBX2    ARPC5L   ZNF274     RAB1B   IFNA10     INE1
cerebellum_1  8.790506 7.055725 10.005485 8.532381 10.485840 5.887900 7.252760
cerebellum_2  7.669598 7.062630 10.138783 8.786666  9.942838 6.236188 7.223891
cerebellum_3  8.933098 6.753196 10.173808 8.651183 10.139486 5.930700 7.060090
cerebellum_4  8.480540 6.913898 10.134898 8.712310 10.250890 6.030034 7.029263
cerebellum_5  8.290392 6.992639 10.069065 8.727731 10.333009 6.122986 7.258358
cerebellum_6  8.850729 7.029022 10.107529 8.363227  9.935499 5.978639 7.250826
cerebellum_7  8.746521 6.842155 10.155704 8.369829  9.984837 5.964979 7.004392
cerebellum_8  8.065408 6.999393 10.068507 8.706500 10.536922 6.055508 7.155549
cerebellum_9  8.691547 6.906382  9.908959 8.676369  9.853805 6.082475 6.986877
cerebellum_10 7.208334 7.173427  9.618588 8.516872 10.102503 6.021254 7.050606
                 CD200    NAA60    NPHP1     MSH4     GCSH GTF2IRD1  ZNF587B
cerebellum_1  8.080438 8.286647 5.127070 5.352777 8.302366 8.224228 6.301106
cerebellum_2  7.514045 8.418362 5.117206 5.550435 8.537879 8.174103 6.292066
cerebellum_3  8.201399 8.312830 5.191294 5.206212 8.692077 7.946782 6.457832
cerebellum_4  7.966936 8.631109 4.972111 5.649283 8.772049 7.902444 6.530335
cerebellum_5  8.193027 8.328019 5.248271 5.388082 7.960648 8.132914 6.460516
cerebellum_6  7.686454 8.596111 5.088556 5.366086 8.201032 8.087098 6.379986
cerebellum_7  8.362530 8.355156 5.118604 5.174136 8.627575 8.044448 6.512262
cerebellum_8  7.374395 8.397848 5.167762 5.406378 8.988391 7.932175 6.056041
cerebellum_9  7.880435 8.524653 5.031103 5.503099 8.714822 8.209901 6.063112
cerebellum_10 7.708453 8.714983 5.169240 5.377176 8.343692 8.078714 6.223415
                  LRP4     CD93    DOCK4  VENTXP1    NFKBIA   PTPRN2  NDUFAF7
cerebellum_1  6.354456 7.974465 8.445142 4.825979 10.053047 7.743550 4.751138
cerebellum_2  6.962965 8.022920 8.484454 4.725126 10.299125 7.715318 4.834661
cerebellum_3  6.933082 7.616126 8.936366 4.853400 10.317383 8.522322 4.718003
cerebellum_4  7.550108 7.480905 8.924463 4.710953 10.165354 8.060123 4.786256
cerebellum_5  7.068039 7.822520 8.867739 4.881134 10.234521 7.829985 4.828078
cerebellum_6  6.781698 7.711707 8.343536 4.674750 10.365539 8.188564 4.607550
cerebellum_7  6.540979 7.515513 8.258671 4.744989  9.680717 8.301487 4.829740
cerebellum_8  7.265358 7.905386 8.739156 4.837362 10.057970 7.607259 4.772154
cerebellum_9  7.409101 7.527801 8.819806 4.664318 10.620316 7.847544 4.754720
cerebellum_10 7.719420 7.772734 8.959571 4.699994 11.099381 8.198948 4.769712
                 GTF2H3     IGKC     DKK4     KXD1      REN ZNF213-AS1  B3GALT1
cerebellum_1  10.565874 5.012194 6.530837 8.362142 6.798718   6.786470 5.742301
cerebellum_2  10.506791 5.228240 6.416643 8.520468 6.814524   6.639399 5.582120
cerebellum_3  10.416941 5.068924 6.306856 8.507586 6.707689   6.522009 5.686974
cerebellum_4  10.594131 5.063542 6.342354 8.630469 6.575020   6.413565 5.592603
cerebellum_5  10.226731 5.007564 6.292900 8.319531 6.850155   6.639925 5.629050
cerebellum_6  10.552203 4.907769 6.510536 8.535453 6.692517   6.594442 5.526634
cerebellum_7  10.735302 5.028542 6.207976 8.368170 6.539912   6.464193 5.520714
cerebellum_8   9.945476 5.049562 6.371213 8.199073 6.767872   6.586747 5.577514
cerebellum_9  10.388563 5.029268 6.249776 8.643714 6.563238   6.344991 5.480907
cerebellum_10 11.056097 5.051620 6.313042 8.777055 6.682053   6.613017 5.849502
                 PTPRJ   ZNF768    FOXA2   SPTLC3 CXorf40A     CST8    STRAP
cerebellum_1  4.926314 6.969382 6.853595 4.776027 8.151040 7.812482 10.93791
cerebellum_2  4.894200 7.151810 7.151272 4.859673 8.491591 7.975800 10.96273
cerebellum_3  5.041269 6.981742 6.515637 4.857793 8.632802 7.859173 11.20159
cerebellum_4  5.033560 7.440737 6.589744 4.893396 8.230016 7.658872 10.95653
cerebellum_5  4.965464 6.949641 6.684891 4.887080 8.346347 7.722985 10.95904
cerebellum_6  5.011119 7.052574 6.731193 4.741811 8.583057 7.963071 11.12952
cerebellum_7  4.995106 7.047896 6.482914 4.742727 8.705370 7.873378 11.13966
cerebellum_8  4.960167 7.053383 6.808531 4.964082 8.354968 7.773020 10.83807
cerebellum_9  4.989213 7.125029 6.762567 4.870499 8.389698 7.787086 10.98175
cerebellum_10 5.085546 7.599178 6.996166 4.912289 8.259854 7.942221 10.47173
                  GJC1    DCHS2   DNAJC3    MARC2   SMG1P2  BTN2A3P     GDF5
cerebellum_1  6.580258 6.166511 5.653966 6.064621 7.457744 8.486605 8.205702
cerebellum_2  6.438512 6.780005 5.694350 5.949254 7.068929 8.507348 8.270465
cerebellum_3  6.710641 6.596702 5.841368 6.046332 8.628356 7.716709 8.071465
cerebellum_4  6.722101 6.490344 5.910709 6.104071 7.737008 7.313492 7.959706
cerebellum_5  6.391719 6.217073 5.945459 6.004200 7.966188 8.772445 8.194792
cerebellum_6  6.924818 6.470107 5.897451 5.937314 8.263997 7.679611 8.289281
cerebellum_7  6.868985 6.306761 6.102559 5.999894 8.025742 7.495059 8.100385
cerebellum_8  6.257464 6.379370 5.907572 6.034809 7.253546 8.639787 8.330882
cerebellum_9  6.354314 6.292924 5.920660 6.055963 7.342485 7.667218 7.957909
cerebellum_10 6.191484 6.448814 5.890377 5.959377 7.022550 7.806702 8.007641
                  GRPR     CES2    LLGL1    CELF3    FOXK2  SHISAL1  CYP3A43
cerebellum_1  8.455286 8.845101 9.528030 8.840165 7.479253 8.371707 5.797829
cerebellum_2  8.651590 8.975798 9.636274 8.633585 7.718413 8.357409 5.578368
cerebellum_3  8.274435 9.082103 9.082141 8.678585 7.777608 8.315518 5.559866
cerebellum_4  8.126002 9.168606 8.713490 8.793149 7.751283 8.301925 5.644913
cerebellum_5  7.677934 8.913266 9.789705 8.532450 7.509819 8.520251 5.656463
cerebellum_6  8.441048 9.054549 9.159955 8.685967 7.557537 8.433164 5.685626
cerebellum_7  8.207664 9.133475 9.061207 8.751484 7.619058 8.659661 5.656607
cerebellum_8  8.132437 8.609865 9.775475 8.642027 7.649195 8.600376 5.781126
cerebellum_9  7.938316 8.615703 9.201940 8.588616 7.517352 8.393678 5.759633
cerebellum_10 8.311138 9.436480 9.137939 8.976205 7.542949 8.828187 5.880271
                TRMT2B    MEP1B    KIF2C    VASH2     VAT1    CLCN1   MRPL24
cerebellum_1  8.514354 6.650071 7.407687 5.417307 9.746103 6.520327 8.956527
cerebellum_2  8.432814 6.809330 7.562065 5.441652 9.637607 6.667578 9.285765
cerebellum_3  8.210949 6.352907 7.242883 5.366250 9.262168 6.441280 8.732482
cerebellum_4  8.251153 6.299184 7.105616 5.344722 9.454266 6.515618 8.919551
cerebellum_5  8.538602 6.643547 7.210712 5.433991 9.484010 6.546961 8.660247
cerebellum_6  8.525676 6.336239 6.941534 5.390762 9.539087 6.767489 8.434468
cerebellum_7  8.524396 6.307881 7.089277 5.374855 9.304878 6.561024 8.663397
cerebellum_8  8.415244 6.687572 7.232508 5.527471 9.616962 6.376162 8.806377
cerebellum_9  8.251018 6.522668 7.224722 5.484626 9.648748 6.507015 8.984581
cerebellum_10 8.131199 6.280904 7.372306 5.246972 9.724268 6.958785 9.243867
               POMGNT1    CASZ1   EEF1E1 NOP14-AS1   MAP2K6   ZNF304 ZSWIM8-AS1
cerebellum_1  7.361528 8.790560 7.972933  5.426191 7.244084 6.687146   9.213941
cerebellum_2  7.317850 8.713832 8.143514  5.427451 7.469902 6.764277   8.718078
cerebellum_3  7.211866 8.684453 8.583544  5.296262 7.383280 6.669848   8.687529
cerebellum_4  7.569181 8.638803 8.278988  5.476347 7.358522 6.965949   8.782983
cerebellum_5  7.331980 8.980657 8.056667  5.380227 7.623572 6.321489   9.047152
cerebellum_6  7.492702 8.759507 8.465026  5.303277 7.133646 6.496521   8.748678
cerebellum_7  7.308789 8.577724 8.726573  5.210481 7.033804 6.726465   8.713206
cerebellum_8  7.307290 8.756642 8.068147  5.344286 7.589024 6.868903   8.832344
cerebellum_9  7.552749 8.344829 8.213815  5.337777 7.194955 7.052466   8.828477
cerebellum_10 7.595524 8.714867 7.343126  5.700025 7.401946 6.370454   9.158708
               CYSLTR2    AGBL2  TMPRSS2    SBNO2    GREM2  SLCO3A1     CILP
cerebellum_1  6.225278 5.306582 8.141082 8.426816 5.536961 8.200231 8.380485
cerebellum_2  6.157653 5.098622 8.454838 8.194302 5.378995 8.289392 8.384034
cerebellum_3  6.236377 5.108646 8.270864 7.944518 5.423788 8.149792 8.288960
cerebellum_4  6.414973 5.133824 7.995359 7.719614 5.463795 8.363383 8.053215
cerebellum_5  6.460352 5.172511 8.147340 8.479167 5.437387 7.994267 8.837406
cerebellum_6  6.198063 5.322719 8.189676 8.088937 5.436582 8.064023 8.449324
cerebellum_7  6.212530 5.069598 8.239358 8.082528 5.524663 8.027738 8.351240
cerebellum_8  6.268201 5.315461 8.120820 8.305418 5.289825 8.187034 8.676219
cerebellum_9  6.377633 5.082158 8.202908 7.890750 5.447331 8.280031 8.251607
cerebellum_10 6.559796 4.902192 8.242961 8.385218 5.250748 7.912775 8.166888
                CHMP2A  ZNF354A   ZNF711    SPAST DKFZP434A062    CRLF2
cerebellum_1  8.024004 5.892942 4.906096 5.221456     7.889895 6.722736
cerebellum_2  8.218670 6.078390 4.659927 5.165527     8.029706 6.870898
cerebellum_3  8.352624 6.070330 5.038314 5.211955     7.748535 6.665408
cerebellum_4  8.528573 5.948707 4.838516 5.130421     7.564397 6.597986
cerebellum_5  8.282092 5.865957 4.965417 5.182767     7.685262 6.883569
cerebellum_6  8.573784 5.806880 4.886453 5.361100     7.619318 6.836500
cerebellum_7  8.331231 5.868212 4.886450 5.245209     7.784696 6.701956
cerebellum_8  8.329623 5.821848 4.785634 5.241567     7.957187 6.899796
cerebellum_9  8.497386 5.874905 4.907845 5.342142     7.778009 6.780163
cerebellum_10 8.441254 5.996863 4.562429 4.933580     8.060893 7.039460
               DDR1-DT    LZTS1    UTP11      MPG EIF4EBP1   TUBA4B    CEP41
cerebellum_1  5.200080 6.186419 6.426536 7.961588 7.534900 7.500291 5.550017
cerebellum_2  5.132652 6.281979 6.843063 8.095060 7.437720 7.644055 5.613439
cerebellum_3  5.294857 6.390746 7.034620 7.926637 7.116311 7.556834 5.678125
cerebellum_4  5.181900 6.295578 7.058111 8.040571 7.124333 7.489814 5.662398
cerebellum_5  5.166854 6.147555 6.613706 7.819527 7.848553 7.623941 5.673379
cerebellum_6  5.250891 6.265193 6.860895 8.074599 7.246575 7.665731 5.850660
cerebellum_7  5.328314 6.262967 6.976421 8.056580 7.130521 7.525990 5.646950
cerebellum_8  5.134514 6.338150 6.695262 7.884789 7.634087 7.594842 5.586926
cerebellum_9  5.242821 6.070799 6.889203 7.750589 7.127139 7.477791 5.654752
cerebellum_10 5.222102 6.403576 6.750020 8.336232 7.455913 7.317250 5.578801
                 PDE4D    MORC1   ANP32E  EPM2AIP1     RELB    OR3A3   ITGA10
cerebellum_1  7.076856 4.516534 6.501942 10.264620 6.754882 7.161436 7.852627
cerebellum_2  7.442426 4.524633 6.654726 10.313289 7.090403 7.024880 7.589330
cerebellum_3  7.754642 4.520485 6.624039 10.432690 6.635781 7.013308 7.404500
cerebellum_4  7.546115 4.514948 6.529203 10.414402 6.512622 7.071974 7.527003
cerebellum_5  7.441256 4.539828 6.531413 10.337909 6.400536 7.144744 7.679309
cerebellum_6  7.378012 4.503659 6.579641 10.648584 6.552681 7.125069 7.708547
cerebellum_7  7.303650 4.477556 6.619453 10.791108 6.629574 7.003716 7.417288
cerebellum_8  7.236634 4.529752 6.691257 10.181536 6.712583 7.159777 7.677199
cerebellum_9  7.682876 4.484412 6.574788 10.674326 6.580459 6.993790 7.647071
cerebellum_10 7.432285 4.548988 6.511560  9.943839 7.065345 7.187632 7.218218
                  LTBR    MICU2     FGD2    ULBP2     FBN1   FAM13A  DNAJC28
cerebellum_1  7.554640 9.027010 6.052199 6.093397 6.363234 9.139429 5.505453
cerebellum_2  7.520515 9.029855 5.943588 5.843041 6.376906 8.844943 5.389779
cerebellum_3  7.558577 9.357674 5.825700 5.835893 6.141250 9.063200 5.434963
cerebellum_4  7.471151 9.392337 5.785530 5.807940 6.089545 8.961922 5.439816
cerebellum_5  7.510951 8.987727 5.946272 5.811728 6.334938 8.975123 5.198910
cerebellum_6  7.734647 9.611773 6.106004 5.817600 6.263068 8.824400 5.155118
cerebellum_7  7.450242 9.501507 5.811077 5.891940 6.264717 8.969945 5.529570
cerebellum_8  7.491269 8.751592 5.859797 5.812909 6.416086 9.038993 5.574817
cerebellum_9  7.454309 9.338857 5.815951 5.918625 6.431467 9.242261 5.438622
cerebellum_10 7.644926 8.240445 5.720879 5.914784 5.970173 9.431524 5.549878
                 APBB3    TBX21   PKNOX1     SPI1      PDC     THRB    HLA-E
cerebellum_1  9.370438 7.231917 6.668406 5.991517 5.128351 8.199290 8.111620
cerebellum_2  9.215742 7.101867 6.569993 5.821928 4.946800 8.109199 8.327917
cerebellum_3  9.202626 6.964818 6.364629 5.728288 5.019310 8.028172 8.190445
cerebellum_4  9.658913 6.970489 6.608711 6.005005 5.058749 7.664513 8.382101
cerebellum_5  9.066938 7.176606 6.600984 6.010436 4.986541 8.029462 8.251289
cerebellum_6  9.102920 6.970245 6.527530 5.986095 4.946139 7.899385 8.342550
cerebellum_7  9.300699 6.882648 6.732374 5.871905 5.002598 7.874857 8.113776
cerebellum_8  9.239492 7.142651 6.540524 5.959515 5.045925 8.018595 8.891877
cerebellum_9  8.927956 6.876946 6.599074 5.886591 4.975361 7.898166 8.610698
cerebellum_10 9.371448 6.869911 6.694190 6.407530 4.845030 7.943370 8.397280
              ADAMTSL4  MYBBP1A    IKBKG  COL15A1   CAMK1G     PATJ   LANCL2
cerebellum_1  8.135283 7.755531 8.079835 5.198133 8.055548 5.961059 7.311401
cerebellum_2  8.012373 7.854000 8.119778 5.075167 8.131530 5.835292 7.561327
cerebellum_3  7.633712 7.618540 8.214490 5.276916 8.100138 6.352313 7.832115
cerebellum_4  7.599147 7.856307 7.943123 5.099198 7.752305 5.895228 7.341256
cerebellum_5  7.414706 7.839068 8.079529 5.267626 8.036525 6.387368 7.362769
cerebellum_6  7.953704 7.852612 8.291062 5.114529 7.946585 6.091220 7.575743
cerebellum_7  7.651207 7.929426 8.242549 5.169237 7.783669 6.934417 7.700253
cerebellum_8  7.536372 7.857709 8.066478 5.016810 8.058580 5.926693 7.467075
cerebellum_9  7.500054 7.694285 8.001849 5.023949 7.656553 6.075758 7.164344
cerebellum_10 7.828774 7.937715 8.186553 4.778880 7.887568 5.728213 7.128549
                 PEX14    ZNF43    TOP3B     SMC2    PTPRR   TGFBR3     DTX4
cerebellum_1  7.129155 5.563989 6.720098 5.739263 5.624637 6.302063 9.676673
cerebellum_2  7.147076 5.568680 6.713188 5.367490 5.678191 6.737697 9.435650
cerebellum_3  7.089070 5.730011 6.518547 6.295638 7.021436 6.343649 9.522546
cerebellum_4  7.350132 5.475319 6.545076 5.634564 6.246326 6.489831 9.665433
cerebellum_5  7.355813 5.483682 6.528850 6.018504 6.000807 6.252029 9.564505
cerebellum_6  6.773318 5.972384 6.465773 5.978982 6.517182 6.204131 9.210070
cerebellum_7  7.131835 5.970797 6.660324 5.976652 6.322177 6.117843 9.649829
cerebellum_8  7.176924 5.601858 6.756251 5.827184 5.644641 6.468321 9.585459
cerebellum_9  7.134087 5.567481 6.648279 5.777049 5.992790 6.273607 9.779382
cerebellum_10 7.016288 5.499277 6.819968 5.321297 5.692942 6.535068 9.499844
                TECPR2     OPN3  POLR2J3     RAB31     IRF8 TNFRSF21    ASTN2
cerebellum_1  7.540317 6.668843 6.707092  8.880537 7.735927 6.654276 5.660501
cerebellum_2  7.578473 6.975572 6.898298  9.376164 7.782416 6.290613 5.730612
cerebellum_3  7.541529 6.521909 6.561407  9.197820 7.881342 6.729857 6.375287
cerebellum_4  7.639033 6.650432 6.939241  9.499674 7.484355 6.332940 6.415515
cerebellum_5  7.572022 6.559182 7.201382  9.138892 7.999689 6.488528 5.766267
cerebellum_6  7.072501 6.382322 6.800875  9.438010 7.299064 6.272174 6.133091
cerebellum_7  7.256381 6.320238 7.100275  8.484666 7.219723 7.158841 6.394563
cerebellum_8  7.681987 6.640336 6.360493  9.719101 7.373606 6.406422 5.711386
cerebellum_9  7.602058 6.716754 6.383891  9.880716 7.427655 7.434815 6.031805
cerebellum_10 7.454688 6.620779 7.115512 10.245844 7.248917 6.051149 5.491261
                ARMCX2     SCIN  C5orf22     CCL2   ZBTB43   GIGYF2   ZFP69B
cerebellum_1  8.481330 5.811826 7.663182 6.444036 7.807040 7.994705 5.130455
cerebellum_2  8.118641 5.768877 7.700008 6.945199 7.834804 7.894170 5.216968
cerebellum_3  8.162826 5.829899 8.233647 6.431893 7.936536 8.346628 4.961334
cerebellum_4  8.624531 5.995586 8.124346 6.265581 8.209451 7.962604 5.004851
cerebellum_5  8.137985 5.847956 7.891707 6.470066 7.957721 8.319120 5.079472
cerebellum_6  8.013301 5.903444 8.073622 6.407633 8.040998 7.882164 4.898261
cerebellum_7  8.448197 5.869461 8.150711 6.311261 7.929311 8.196310 4.977986
cerebellum_8  8.447225 5.898654 7.903838 6.363242 7.747902 8.429935 5.060316
cerebellum_9  8.672863 5.912652 7.888392 6.232460 7.740454 8.004569 4.894312
cerebellum_10 8.463792 5.863480 7.630649 6.530860 8.123684 7.826356 4.981989
                 TFB1M   ERVH-6    H3F3A   GRAMD4    OR1D4 TNFRSF11A   ZBTB7C
cerebellum_1  6.600983 7.170327 11.77141 6.167753 6.157668  5.932049 4.960943
cerebellum_2  6.490166 7.413146 11.97541 6.314656 6.176002  5.984211 5.028853
cerebellum_3  6.446882 6.797505 12.16264 6.428454 6.034306  5.795667 4.933704
cerebellum_4  6.671594 6.624923 12.00310 6.634284 6.030267  5.802075 5.025128
cerebellum_5  6.529456 6.885288 11.79964 6.396996 5.899683  5.563297 4.887328
cerebellum_6  6.431779 6.544283 12.04783 6.389655 5.957897  5.942273 5.028382
cerebellum_7  6.609042 6.714332 12.07494 6.352941 5.990853  5.794418 4.978274
cerebellum_8  6.488921 6.817856 11.90416 6.268386 6.063647  5.698115 4.953371
cerebellum_9  6.797053 6.895017 12.17077 6.616104 6.121938  5.870699 5.015716
cerebellum_10 6.793036 6.968049 12.11206 6.256752 6.115158  5.915580 5.047515
                   OTC    TRIP4     RARB   PDLIM5   SORCS3   MYCNOS      RCN2
cerebellum_1  6.197013 7.140038 7.356519 5.968331 5.692614 6.351369  9.319886
cerebellum_2  6.299289 6.980417 7.396406 6.018704 5.493578 6.847629  9.354271
cerebellum_3  6.039490 7.244516 7.089845 6.023023 5.759787 6.387823 10.038108
cerebellum_4  5.983596 7.212249 7.217095 5.937750 5.813368 6.211362  9.925286
cerebellum_5  5.928799 7.417639 7.202117 6.209718 5.372443 6.418935  9.341694
cerebellum_6  6.364419 7.056717 7.484667 6.083274 5.531740 6.204634  9.687795
cerebellum_7  6.019924 7.257768 7.285947 5.961576 5.690544 6.202727  9.896471
cerebellum_8  6.095270 7.349791 7.287226 6.175866 5.690270 6.311451  9.330310
cerebellum_9  5.984173 7.374037 7.400311 6.024129 5.605414 6.282154  9.440263
cerebellum_10 5.974306 6.968588 6.824252 6.081013 5.614411 6.312606  9.375808
                 EMID1      DDT    WDR45  FBXW4P1    MYCBP    EXOC3   IL10RA
cerebellum_1  8.419577 7.204615 8.723059 5.978130 5.714410 8.364197 7.084475
cerebellum_2  8.525324 7.283988 8.789790 6.064737 5.597535 8.868938 7.014965
cerebellum_3  8.199029 7.544834 8.779571 5.595309 5.749240 8.514287 6.633680
cerebellum_4  8.118662 7.239984 8.813066 6.000582 5.765867 8.562047 6.652929
cerebellum_5  8.461065 7.088698 8.829595 5.749772 5.983365 8.853253 6.722309
cerebellum_6  8.506635 7.611979 8.573793 5.953585 5.881637 8.573542 6.863938
cerebellum_7  8.266434 7.529837 8.496090 5.965093 5.792337 8.641560 6.576328
cerebellum_8  8.460376 7.299379 8.582119 6.131020 5.700683 8.514662 6.943270
cerebellum_9  8.505248 7.144527 8.476017 6.018434 5.826719 8.646289 6.811057
cerebellum_10 8.600893 7.257731 8.972367 6.309372 5.699481 8.711652 6.902745
                 ABCC5    SPAG4    KLF11     DLX6     FZD2    CBARP     TCN2
cerebellum_1  9.491850 6.072461 7.636539 6.290753 5.484414 4.834216 7.815282
cerebellum_2  9.146650 6.116151 7.938652 6.167327 5.485431 4.819079 7.740533
cerebellum_3  9.117225 5.887079 8.298301 6.002976 5.213344 4.867569 7.715703
cerebellum_4  9.553074 5.873882 8.191637 6.048914 5.520238 4.793411 7.719972
cerebellum_5  9.353503 6.130942 7.437114 6.098194 5.319185 4.828373 7.800265
cerebellum_6  9.150269 5.961552 7.879344 5.931433 5.490302 4.836477 7.925131
cerebellum_7  9.379379 5.835976 7.958044 6.010180 5.401587 4.932055 7.816689
cerebellum_8  9.490857 6.018110 8.106415 6.160825 5.351064 4.827541 7.872099
cerebellum_9  9.668587 5.734400 7.479011 5.873313 5.352725 4.878709 7.570294
cerebellum_10 9.566086 6.132262 7.301130 6.137280 5.607477 4.955547 8.147068
                 GATA2   BCKDHB     PPM1B TNFRSF13B     HAMP    KLRD1    AP3B2
cerebellum_1  7.260657 5.436517 10.221053  8.350300 6.837616 6.661025 8.042945
cerebellum_2  7.076923 5.551104 10.029349  8.356537 6.124379 6.736513 8.669072
cerebellum_3  7.024526 5.623502 10.328870  8.098375 6.339130 6.767210 8.582375
cerebellum_4  6.907938 5.668993 10.458888  8.393742 5.998325 6.620470 8.699351
cerebellum_5  7.221100 5.617695 10.139463  8.202332 5.896739 6.888108 8.181512
cerebellum_6  7.209324 5.512732 10.122220  8.406143 6.436601 6.735630 8.612968
cerebellum_7  6.925773 5.529524 10.211507  8.289835 6.094383 6.674751 8.462641
cerebellum_8  7.208919 5.730528 10.397497  8.155947 6.221422 6.737932 7.817910
cerebellum_9  6.987909 5.690867 10.265408  8.137793 5.853609 6.757327 7.927411
cerebellum_10 6.621956 5.619669  9.941577  8.763273 6.046734 6.397228 8.228289
                  DCTN3    ZNF45     LTA4H    LRIF1    CXCL2    REEP1      WRB
cerebellum_1  10.263485 4.970089 10.059982 6.113295 5.615990 8.837536 9.409692
cerebellum_2  10.305285 4.924837  9.841166 5.975025 6.001019 9.088455 9.003134
cerebellum_3  10.469188 5.004060  9.707575 5.819456 5.481555 9.625351 9.600064
cerebellum_4  10.215975 4.959983 10.091814 6.033357 5.235723 9.540876 9.626273
cerebellum_5  10.263711 5.002893  9.921711 6.252941 5.422702 9.108483 9.384502
cerebellum_6  10.323276 5.024154  9.761979 5.833527 5.441802 9.256549 9.259236
cerebellum_7  10.239006 5.066041  9.810411 6.428893 5.340037 9.796348 9.623909
cerebellum_8  10.387034 5.062066  9.868494 6.464319 5.225535 8.817191 9.533709
cerebellum_9  10.185555 5.062150 10.162251 6.240446 5.367240 8.902997 9.760705
cerebellum_10  9.861359 4.839890 10.240862 6.019111 5.653369 9.036478 9.127156
                 RAB5B  SMARCD1    TFB2M    CNTN6    FOXE3    CEP55    ELAC2
cerebellum_1  9.800997 7.562201 7.255611 5.269896 5.955532 4.897752 6.079956
cerebellum_2  9.513469 7.663300 6.886540 5.790230 5.970289 5.000637 6.418794
cerebellum_3  9.798809 7.404282 7.470159 6.047562 6.213775 4.887407 6.191465
cerebellum_4  9.764218 7.282060 7.065134 5.726222 6.050173 4.824391 5.999839
cerebellum_5  9.649089 7.283802 7.307760 5.677634 6.010784 5.044817 5.963875
cerebellum_6  9.617166 7.350214 6.697971 5.603453 6.134978 5.029390 6.167507
cerebellum_7  9.636420 7.361841 7.172003 6.259564 6.008513 4.836065 6.134210
cerebellum_8  9.771078 7.477645 7.175151 5.300010 5.972055 5.047937 5.988995
cerebellum_9  9.850741 7.147315 7.341993 5.554570 5.872406 4.831743 6.151127
cerebellum_10 9.829828 7.484508 6.749710 5.375243 6.029570 4.739313 5.948467
               ZNF767P     PCBP4 HNRNPUL1    KIFAP3  TRAV8-3    CLCN5     BIN1
cerebellum_1  8.601292 10.022282 8.850211  9.714242 6.043773 5.560286 10.54258
cerebellum_2  8.541690 10.237201 8.953656  9.573385 6.129586 5.419966 10.71771
cerebellum_3  8.541150  9.990241 8.935088 10.208341 5.875568 5.501589 10.53290
cerebellum_4  8.992370 10.521203 9.063872  9.678353 5.836487 5.447594 10.87906
cerebellum_5  8.587262  9.877068 8.909095  9.748895 5.925916 5.488435 10.36846
cerebellum_6  8.683725 10.049515 8.774191  9.807927 5.913982 5.619431 10.93703
cerebellum_7  8.670264  9.970468 8.758384  9.886134 5.873790 5.603866 10.72160
cerebellum_8  8.421311 10.181025 9.026603  9.778042 6.092231 5.268357 10.59926
cerebellum_9  8.545993  9.871277 8.887223  9.749845 5.901606 5.402220 10.97578
cerebellum_10 8.736707 10.297544 9.353272  9.014295 5.903367 5.366346 10.63464
                  EGFR     BZW1    NDUFV1     WTAP     REC8    KCMF1   LILRB5
cerebellum_1  7.083953 8.307588 10.044857 7.700130 9.276763 9.632484 5.201560
cerebellum_2  7.906025 8.280252 10.236947 7.827493 9.359595 9.833136 5.208509
cerebellum_3  7.199526 8.706690  9.993538 8.100767 9.313049 9.702311 5.401308
cerebellum_4  8.276389 8.202199 10.183596 7.669179 9.378431 9.693084 5.237373
cerebellum_5  7.570613 8.309164 10.018255 8.103955 8.994519 9.916846 5.403427
cerebellum_6  7.781624 8.455080 10.177341 7.431457 9.349163 9.744373 5.351911
cerebellum_7  6.854474 8.660172 10.115562 7.908646 9.216704 9.653321 5.376417
cerebellum_8  8.346898 8.456520  9.976792 8.249864 9.200168 9.428519 5.465783
cerebellum_9  8.446770 8.210160  9.969067 7.899007 9.060816 9.589735 5.239246
cerebellum_10 8.843682 7.663425  9.886651 7.540597 9.234672 9.513892 5.176057
                 TFCP2    CDH12    EHMT2 LINC01558   ZNHIT3    DBF4B    GLUD1
cerebellum_1  6.510235 5.478375 8.278533  6.252060 9.003876 5.769401 8.483594
cerebellum_2  6.617030 5.246861 8.963138  6.138301 8.743393 5.936784 9.029178
cerebellum_3  6.580162 5.560792 8.593832  6.200862 9.190041 5.730704 8.668909
cerebellum_4  6.821375 5.363574 9.105989  6.021273 9.062425 5.623541 8.943708
cerebellum_5  6.586001 6.174987 8.258163  6.445312 8.906627 5.442350 8.844178
cerebellum_6  6.788850 5.566791 8.636312  6.437440 8.928366 5.658629 9.089343
cerebellum_7  6.827405 5.308485 8.902480  6.296585 9.029706 5.777631 8.668321
cerebellum_8  6.654547 4.986748 8.562931  6.063496 9.102419 5.600882 9.183419
cerebellum_9  6.712364 5.194185 8.701209  6.379799 9.113444 5.674261 9.308822
cerebellum_10 6.036394 5.234720 8.837342  6.182145 8.422315 5.721346 8.991230
                 ADRB2    FBXW4      SPP1      F2R      SDF4   GALNT8  TMEM63A
cerebellum_1  7.040313 8.610730 11.065803 4.629086 10.221554 6.433695 6.762792
cerebellum_2  7.229260 8.599544  7.013212 4.703684 10.219990 6.509343 6.745595
cerebellum_3  6.965293 8.674405  8.662279 4.559639 10.177339 6.328374 6.839130
cerebellum_4  6.848412 8.891241  8.102981 4.564036 10.426493 6.361397 6.555226
cerebellum_5  6.790365 8.638445  9.428422 4.701921 10.085457 6.352388 6.834483
cerebellum_6  6.901536 8.974827  8.828863 4.580162 10.299838 6.455319 6.636656
cerebellum_7  6.777231 8.784737  9.091320 4.583330  9.956574 6.274584 6.821190
cerebellum_8  6.895350 8.689898  9.071951 4.695389 10.098908 6.511459 6.760665
cerebellum_9  6.712909 8.985205 11.264768 4.625259 10.198665 6.204632 7.471069
cerebellum_10 7.156409 8.937919  7.972399 4.713284 10.190298 6.257040 6.929661
                  BSCL2     GZMM    THSD4     PRLR  PLEKHJ1     TLE3    PANK2
cerebellum_1   9.952449 6.443002 5.922374 4.622496 8.454756 5.824787 8.718452
cerebellum_2  10.136271 6.633884 6.344804 4.579061 8.635231 6.039730 8.762630
cerebellum_3  10.240502 6.528527 6.008704 4.636049 8.588767 5.931742 8.757278
cerebellum_4  10.273108 6.340142 5.998217 4.668546 8.403214 5.712891 8.795656
cerebellum_5  10.107644 6.678065 6.248010 4.566313 8.656308 5.809229 8.704472
cerebellum_6   9.860423 6.787333 6.345705 4.549893 8.501389 5.857296 8.868688
cerebellum_7  10.341734 6.466158 6.004096 4.670552 8.670544 5.797641 8.735693
cerebellum_8  10.160243 6.531749 6.187625 4.609949 8.380579 5.806203 8.702267
cerebellum_9   9.937901 6.352714 6.017607 4.561663 8.428422 5.894831 8.542660
cerebellum_10 10.273235 6.904421 6.184262 4.652401 8.693723 5.787472 8.628495
                  SKP1   TOMM70 KIAA1324  PCDHB12     CPA4    TRPV2   CHCHD2
cerebellum_1  11.45558 7.412681 6.173239 7.330765 8.565729 6.925835 11.70191
cerebellum_2  11.29520 6.833040 6.088014 7.354124 8.567492 6.990294 11.85371
cerebellum_3  11.61239 7.549532 5.984550 7.078666 8.418580 6.841210 11.68091
cerebellum_4  11.43709 7.112513 5.835209 7.166445 8.177593 6.720032 11.72392
cerebellum_5  11.29608 7.527022 5.985542 7.263494 8.804276 6.650958 11.46124
cerebellum_6  11.80928 7.409253 5.720563 7.399827 8.724149 6.635182 11.82858
cerebellum_7  11.60241 7.548364 5.921916 7.211696 8.523836 6.701801 11.73383
cerebellum_8  11.20900 7.093286 5.994804 7.078496 8.614645 6.842448 11.66797
cerebellum_9  11.53226 7.335864 5.915881 7.077904 8.520384 6.664842 11.64791
cerebellum_10 11.28085 6.668287 5.795449 7.249465 7.981458 7.090460 11.31622
                 TRPC6    MYO1D   SLURP1     ALG9    ZC4H2  KIR2DL3      IVL
cerebellum_1  4.957596 5.087307 6.523595 6.285564 8.686987 7.267006 7.259913
cerebellum_2  5.063026 5.081363 6.765292 6.460307 8.676383 7.295251 7.362624
cerebellum_3  4.962512 5.124884 6.443617 6.358322 8.528252 7.138351 7.104078
cerebellum_4  4.929839 5.150787 6.284821 6.539948 8.251697 7.055081 7.057660
cerebellum_5  5.066726 5.141932 6.591144 6.319003 8.717467 7.367454 7.473140
cerebellum_6  4.923003 5.226527 6.722563 6.478912 8.485100 7.370852 7.203774
cerebellum_7  4.965629 5.149040 6.448707 6.472224 8.474232 7.124895 6.963790
cerebellum_8  5.045683 5.088062 6.642624 6.305869 8.579784 7.099402 7.545133
cerebellum_9  4.885506 5.529998 6.492132 6.506910 8.396716 7.162363 7.179918
cerebellum_10 4.897716 4.973934 6.595117 6.361298 8.230844 7.174962 7.061225
                 BAMBI   SLC7A6  SLC17A1     CCL3     PHF8  KIR3DL3    SARS2
cerebellum_1  6.489850 5.593892 6.958186 6.207895 7.370194 7.265660 7.412026
cerebellum_2  6.923374 5.601564 6.863409 7.115482 7.352131 7.430712 7.676224
cerebellum_3  6.995669 5.543316 6.847377 5.940453 7.296964 7.475161 7.326263
cerebellum_4  6.803243 5.475850 6.736858 6.044319 7.384879 7.182545 7.309168
cerebellum_5  6.543107 5.534156 6.923578 6.102948 7.240419 7.251760 7.558320
cerebellum_6  6.412329 5.717078 6.883601 5.724371 7.147063 7.223741 7.680238
cerebellum_7  6.538764 5.678116 6.740812 6.000318 7.267486 7.311015 7.472560
cerebellum_8  6.532296 5.541711 6.958241 6.083122 7.181746 7.321546 7.662863
cerebellum_9  6.839555 5.509378 6.695759 5.873135 7.298600 7.321541 7.388574
cerebellum_10 6.708779 5.424847 6.606631 5.827269 7.256492 7.037549 7.355846
               PIP4K2C  S100A13    EPHA1    MFGE8      OAZ2    PCBP3    POLA1
cerebellum_1  8.994165 8.640223 7.017747 8.439859 10.233591 8.457219 7.347544
cerebellum_2  9.211184 9.175377 7.098755 8.627736  9.840514 8.784941 7.476239
cerebellum_3  9.268666 8.875138 6.742484 8.191681 10.060973 8.523428 7.299006
cerebellum_4  9.016394 8.705979 6.850879 8.280976  9.913842 8.210854 7.453407
cerebellum_5  9.232840 8.852406 6.838669 8.043418 10.028252 8.758295 7.253716
cerebellum_6  9.130068 8.576129 6.718682 7.925071 10.103028 8.752971 7.348682
cerebellum_7  9.317062 8.274288 6.910883 8.209641 10.035968 8.747948 7.164534
cerebellum_8  9.396430 9.157773 6.814330 8.146344 10.011552 8.348954 7.098703
cerebellum_9  9.017730 8.968114 6.872103 8.126090 10.140006 8.210992 7.581902
cerebellum_10 9.103381 9.606449 6.991603 8.340146  9.522015 8.104129 7.289444
               KREMEN2   CYP7B1   LILRB3     GSAP
cerebellum_1  8.391655 4.760017 8.230182 6.740385
cerebellum_2  8.260828 4.952373 8.332502 6.390683
cerebellum_3  8.275763 4.796232 7.978194 6.677038
cerebellum_4  8.276021 4.963021 7.894200 6.815246
cerebellum_5  8.473418 4.871638 8.129660 6.996641
cerebellum_6  8.624586 4.898603 8.182295 6.665318
cerebellum_7  8.196416 4.808854 7.987061 7.050766
cerebellum_8  8.434057 4.980173 8.137250 7.491194
cerebellum_9  8.149535 4.857099 8.061415 6.504260
cerebellum_10 8.364969 4.885452 8.384932 6.722921</code></pre>
</div>
</div>
<p>After exploring the data, I have found 94500 numbers in matrix = 189 samples × 500 genes. Next, I decided to perform the classical PCA analysis and plots for gene expression data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(x)                  </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>pca_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">PC1 =</span> pca<span class="sc">$</span>x[,<span class="dv">1</span>],</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">PC2 =</span> pca<span class="sc">$</span>x[,<span class="dv">2</span>],</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">tissue =</span> y</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot PC1 vs PC2</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pca_data, <span class="fu">aes</span>(<span class="at">x =</span> PC1, <span class="at">y =</span> PC2, <span class="at">color =</span> tissue)) <span class="sc">+</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PCA of gene expression"</span>, <span class="at">x =</span> <span class="st">"PC1"</span>, <span class="at">y =</span> <span class="st">"PC2"</span>) <span class="sc">+</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="starter-analysis-exercise_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I chose to explore basic tissue-specific expression patterns. Specifically, I addressed whether brain tissues (e.g., cerebellum and hippocampus) share more highly expressed genes with each other than they do with non-brain tissues.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># AI Disclosure: I used ChatGPT in this step to review the code for generating the matrix and converting expression matrix (189 samples × 500 genes) into a data frame 'as.data.frame' : </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># For each gene, I computed average expression across all samples within each tissue</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>tissue_avg_matrix <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">split</span>(<span class="fu">as.data.frame</span>(x), y), colMeans))</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute correlation matrix between tissues</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(<span class="fu">t</span>(tissue_avg_matrix))  <span class="co"># genes as rows</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign tissue names to rows and columns</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>tissue_names <span class="ot">&lt;-</span> <span class="fu">rownames</span>(tissue_avg_matrix)</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(cor_matrix) <span class="ot">&lt;-</span> <span class="fu">colnames</span>(cor_matrix) <span class="ot">&lt;-</span> tissue_names</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot correlation heatmap</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a><span class="fu">pheatmap</span>(cor_matrix,</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">main =</span> <span class="st">"Correlation of average gene expression"</span>,</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">clustering_distance_rows =</span> <span class="st">"correlation"</span>,</span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">clustering_distance_cols =</span> <span class="st">"correlation"</span>,</span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">display_numbers =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="starter-analysis-exercise_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Last, I tried to stistically test weather brain tissues share a higher number of highly expressed genes compared to other non-brain tissues.</p>
<p>Question: is the average correlation between brain and non-brain tissues statistically lower than the correlation between the two brain tissues?</p>
<p>Here I will be testing whether a set of correlations (brain–non-brain) is statistically lower on average than a reference value (brain–brain).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Do brain tissues exhibit more similar gene expression patterns with each other than they do with non-brain tissues?</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>brain_tissues <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"cerebellum"</span>, <span class="st">"hippocampus"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>non_brain_tissues <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(tissue_names, brain_tissues)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation between brain tissues</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>brain_brain_cor <span class="ot">&lt;-</span> cor_matrix[<span class="st">"cerebellum"</span>, <span class="st">"hippocampus"</span>]</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlations between each brain tissue and all non-brain tissues</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>brain_non_cor <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  cor_matrix[<span class="st">"cerebellum"</span>, non_brain_tissues],</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  cor_matrix[<span class="st">"hippocampus"</span>, non_brain_tissues]</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a><span class="co"># One-sample t-test: is brain–non-brain correlation &lt; brain–brain correlation?</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(brain_non_cor, <span class="at">mu =</span> brain_brain_cor, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  brain_non_cor
t = -9.0898, df = 9, p-value = 3.936e-06
alternative hypothesis: true mean is less than 0.9553056
95 percent confidence interval:
      -Inf 0.8610922
sample estimates:
mean of x 
 0.837293 </code></pre>
</div>
</div>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>